// 3.54.0: tatsächlicher KI-Aufruf/Fallback und Lesbarkeit des neuen Panels.
const h = require('./harness'); let pass = 0, fail = 0; const check = (name, ok, detail = '') => { ok ? pass++ : fail++; console.log(`${ok ? '✓' : '✗'} ${name}${detail ? ' — ' + detail : ''}`); };
(async () => { let browser;
  try {
    await h.setup(); browser = await h.launch(); const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, acceptDownloads: true }), page = await ctx.newPage(), errors = [], requests = []; let mode = 'good'; page.on('pageerror', e => errors.push(e.message));
    await page.route('http://127.0.0.1:8999/**', async route => { const headers = { 'access-control-allow-origin': h.URL_BASE, 'access-control-allow-methods': 'GET, POST, OPTIONS', 'access-control-allow-headers': 'authorization,content-type' }; if (route.request().method() === 'OPTIONS') return route.fulfill({ status: 204, headers }); if (!route.request().url().endsWith('/v1/orderflow/explain')) return route.fulfill({ status: 503, headers, contentType: 'application/json', body: '{"ok":false}' }); const body = route.request().postDataJSON(); requests.push(body); const current = mode;
      if (current === 'slow') await new Promise(r => setTimeout(r, 9000));
      return route.fulfill({ status: current === 'failure' ? 503 : 200, headers, contentType: 'application/json', body: JSON.stringify({ ok: current !== 'failure', signal: current === 'wrong' ? body.context.signal === 'buy' ? 'sell' : 'buy' : body.context.signal, text: 'Prüferklärung: Das berechnete Signal bleibt bestehen.' }) }).catch(() => {});
    });
    await page.goto(h.URL_BASE + '/weather-widget-v2.html'); await page.waitForFunction(() => window.__pdf2?.feed.quote()?.fresh && __pdf2.feed.state.series['5m']?.length > 50);
    const connect = () => page.evaluate(() => { for (const [id, value] of [['svc-url', 'http://127.0.0.1:8999'], ['svc-key', 'k'.repeat(43)]]) { const input = document.getElementById(id); input.value = value; input.dispatchEvent(new Event('change', { bubbles: true })); } }); await connect(); await page.click('.of-signal-settings>summary'); await page.getByLabel('KI-Erklärung über eigenen 24/7-Dienst').check();
    await page.getByLabel('KI-Modell', { exact: true }).fill('allowed'); await page.getByRole('button', { name: 'Einstellungen speichern', exact: true }).click(); await page.click('.of-signal-settings>summary'); await page.waitForFunction(() => document.querySelector('.of-signal-explanation').textContent.startsWith('Prüferklärung'));
    check('Eigener Dienst bekommt fertigen Kontext, beide BTC-Stufen und Zustand', requests.length === 1 && requests[0].context.model === 'orderflow-1' && requests[0].context.groups.length === 5 && 'one' in requests[0].context.btc && 'five' in requests[0].context.btc && !('candles' in requests[0].context));
    check('KI erklärt, Regel-Badge und Score bleiben unverändert', await page.evaluate(() => /Regeln \+ KI/.test(document.getElementById('of-signal').textContent) && document.getElementById('of-signal-badge').textContent === ({ buy: 'Kaufen', sell: 'Verkaufen · Short eröffnen', wait: 'Warten', hold: 'Halten', secure: 'Absichern', exit: 'Aussteigen' })[__pdf2.view.frame.result.signal]));
    await page.waitForTimeout(1500); check('Mehrere echte Ticks lösen keine weitere KI-Anfrage aus', requests.length === 1);
    const reload = async kind => { mode = kind; await page.reload(); await page.waitForFunction(() => window.__pdf2?.feed.quote()?.fresh); await connect(); };
    const wrongResponse = page.waitForResponse(r => r.url().endsWith('/v1/orderflow/explain')); await reload('wrong'); await wrongResponse; await page.waitForFunction(() => !document.querySelector('.of-signal-explanation').textContent.startsWith('Prüferklärung') && document.getElementById('of-signal').textContent.includes('Nur Regeln'));
    check('Abweichendes KI-Signal verworfen, niemals als neues Signal übernommen', !await page.locator('.of-signal-explanation').textContent().then(t => t.startsWith('Prüferklärung')) && requests.some(r => r.model === 'allowed'));
    const failedResponse = page.waitForResponse(r => r.url().endsWith('/v1/orderflow/explain')); await reload('failure'); await failedResponse; await page.waitForFunction(() => document.getElementById('of-signal').textContent.includes('Nur Regeln')); check('Nicht eingerichteter Dienst liefert weiterhin Regeltext', await page.evaluate(() => document.querySelector('.of-signal-explanation').textContent.length > 10 && document.getElementById('of-signal').textContent.includes('Nur Regeln')));
    const start = requests.length; await reload('slow'); await page.waitForFunction(() => document.getElementById('of-signal').textContent.includes('Erklärung wird geladen'), null, { timeout: 10000 }); await page.waitForFunction(() => !document.getElementById('of-signal').textContent.includes('Erklärung wird geladen'), null, { timeout: 10000 });
    check('8-s-Zeitlimit: Erklärung fällt aus, Signal und UI laufen weiter', requests.length > start && await page.evaluate(() => !__pdf2.view.boundary.failed && document.querySelector('.of-signal-explanation').textContent.length > 10 && document.getElementById('of-signal').textContent.includes('Nur Regeln')));
    mode = 'good'; await page.fill('#symbol', 'ETH'); await page.press('#symbol', 'Enter'); await page.waitForFunction(() => __pdf2.feed.state.symbol === 'ETHUSDT'); await page.waitForTimeout(1500); check('Verspäteter Text des vorherigen Coins erscheint nicht bei ETH', !await page.locator('.of-signal-explanation').textContent().then(t => t.startsWith('Prüferklärung')));
    await page.evaluate(() => { document.documentElement.dataset.background = 'custom'; });
    for (const entry of await page.evaluate(() => __sdAppearance.palette)) { await page.evaluate(color => { const palette = document.querySelector(`[data-background-color="${color}"]`); palette.click(); }, entry.color);
      check(`${entry.name}: BTC/Signal/Kerzenhinweise AA-Kontrast`, await page.evaluate(() => { const cs = getComputedStyle(document.documentElement), v = n => cs.getPropertyValue('--' + n).trim(); return ['up-text', 'down-text', 'warn-text', 'muted', 'text'].every(fg => __sdAppearance.contrast(v(fg), v('surface')) >= 4.5); }));
    }
    await page.screenshot({ path: '/tmp/scalpdesk-354-panel-mobile.png', fullPage: true }); check('Keine JavaScript-Laufzeitfehler', errors.length === 0, errors.join(' | ')); await ctx.close(); console.log(`${pass}/${pass + fail} bestanden`); process.exitCode = fail ? 1 : 0;
  } catch (e) { console.error('Abbruch', e); process.exitCode = 1; } finally { if (browser) await browser.close(); await h.teardown(); }
})();
