// Adaptive AI-Grid: echter öffentlicher Worker, native Bot-Persistenz, Mobile und Schutz.
const h = require('./harness'); let pass = 0, fail = 0;
const check = (name, ok, info = '') => { ok ? pass++ : fail++; console.log(`${ok ? '✓' : '✗'} ${name}${info ? ' — ' + String(info).slice(0, 350) : ''}`); };
(async () => { let browser;
  try {
    await h.setup(); browser = await h.launch(); const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true }), page = await ctx.newPage(), errors = [], calls = [];
    let apiError = null;
    page.on('pageerror', e => errors.push(e.message));
    await ctx.route('https://api.bitget.com/**', async route => {
      const request = route.request(), u = new URL(request.url()), at = Date.now(), step = 900000; calls.push({ path: u.pathname, method: request.method(), symbol: u.searchParams.get('symbol'), params: Object.fromEntries(u.searchParams), headers: request.headers() });
      if (apiError === 'offline') return route.abort('internetdisconnected');
      if (apiError === '429') return route.fulfill({ status: 429, headers: { 'retry-after': '2', 'access-control-expose-headers': 'Retry-After' }, body: '' });
      let data;
      if (u.pathname.endsWith('/contracts')) data = [{ symbol: u.searchParams.get('symbol'), baseCoin: 'BTC', quoteCoin: 'USDT', symbolType: 'perpetual', symbolStatus: 'normal', supportMarginCoins: ['USDT'], pricePlace: '2', priceEndStep: '1', sizeMultiplier: '0.001', minTradeNum: '0.001', minTradeUSDT: '5' }];
      else if (u.pathname.endsWith('/ticker')) data = [{ symbol: u.searchParams.get('symbol'), bidPr: '99.99', askPr: '100.01', markPrice: '100', ts: String(at) }];
      else if (u.pathname.endsWith('/history-candles')) { const end = Number(u.searchParams.get('endTime')); data = Array.from({ length: Number(u.searchParams.get('limit')) }, (_, i) => [String(end - (i + 1) * step), '100', '101', '99', '100', '100', '10000']); }
      else if (u.pathname.endsWith('/candles')) data = [[String(Math.floor(at / step) * step), '100', '101', '99', '100', '1', '100']];
      else return route.fulfill({ status: 400, body: JSON.stringify({ code: 'unbekannt' }) });
      return route.fulfill({ contentType: 'application/json', body: JSON.stringify({ code: '00000', requestTime: at, data }) });
    });
    await page.goto(h.URL_BASE + '/weather-widget-v2.html'); await page.waitForFunction(() => window.__g12?.view.state.confirmed && !__g12.view.state.busy); await page.click('#ki-bot-tab'); await page.waitForFunction(() => !__g12.view.state.busy);
    check('Neue Strategie wählbar, bestehender Konfluenz-Default unverändert', await page.inputValue('#bot-strategy') === 'confluence' && await page.locator('#bot-strategy option[value=adaptive-grid]').textContent() === 'Adaptive AI-Grid (Rauschen-Trader)' && !calls.length);
    await page.selectOption('#bot-direction', 'short'); await page.fill('#bot-maxPositions', '2'); await page.selectOption('#bot-strategy', 'adaptive-grid');
    check('Grid erzwingt genau einen Long-Modellbestand; Einstellungen als eigener Klappbereich', await page.evaluate(() => document.getElementById('bot-direction').value === 'long' && document.getElementById('bot-direction').disabled && document.getElementById('bot-maxPositions').value === '1' && document.getElementById('bot-grid-settings').open && !document.getElementById('bot-grid-settings').hidden && document.getElementById('bot-group-protection').hidden));
    check('Dump-Default Pause und Gebührenszenario frei editierbar; Kapital bleibt leer', await page.inputValue('#bot-gridDump') === 'pause' && await page.inputValue('#bot-gridCapital') === '' && await page.inputValue('#bot-gridMaker') === '0.1');
    await page.selectOption('#bot-strategy', 'po3');
    check('Rückkehr zu bestehendem Profil erhält vorherige Richtung und Positionszahl', await page.inputValue('#bot-direction') === 'short' && await page.inputValue('#bot-maxPositions') === '2' && await page.evaluate(() => document.getElementById('bot-grid-settings').hidden && !document.getElementById('bot-group-protection').hidden));
    await page.selectOption('#bot-strategy', 'adaptive-grid'); await page.click('#bot-preset'); await page.fill('#bot-leverage', '3');
    check('Bewusste Übungswerte füllen Grid-Kapital, aktivieren keinen Lauf', await page.inputValue('#bot-gridCapital') === '100' && await page.evaluate(() => !__g12.view.state.confirmed.enabled && !__g12.view.state.confirmed.run));
    await page.fill('#bot-gridCapital', '80'); await page.click('#bot-preset'); check('Eigener Grid-Kapitalwert bleibt beim Übungsbutton erhalten', await page.inputValue('#bot-gridCapital') === '80');
    await page.check('#bot-gain-enabled');
    await page.click('#bot-enable'); await page.waitForFunction(() => __g12.view.state.confirmed.enabled && !__g12.view.state.busy); await page.click('#bot-start'); await page.waitForFunction(() => __g12.view.state.confirmed.run?.grid && !__g12.view.state.busy);
    check('Start speichert Long-Grid-Konfiguration, erzeugt weder Positionen noch Börsenabrufe', await page.evaluate(() => __g12.view.state.confirmed.settings.grid.capitalUSDT === '80' && __g12.view.state.confirmed.run.grid.inventory.quantity === '0' && !__g05.state.positions.length && !__g05.state.demoPositions.length && !__g12.view.state.confirmed.run.automaticTrading) && !calls.length);
    await page.click('#ki-price-tab'); await page.fill('#symbol', 'ETH'); await page.click('#market-form button[type=submit]'); await page.waitForFunction(() => __g05.state.symbol === 'ETHUSDT'); await page.click('#ki-bot-tab'); await page.waitForFunction(() => !__g12.view.state.busy);
    check('Chartwechsel ändert nicht den bestätigten Coin des Grid-Laufs', await page.evaluate(() => __g05.state.symbol === 'ETHUSDT' && __g12.view.state.confirmed.run.grid.scope.instrument === 'BTCUSDT'));
    await page.click('#bot-grid-check'); await page.waitForFunction(() => __g12.view.state.confirmed.run.grid.plan && !__g12.view.state.busy, null, { timeout: 25000 });
    check('Echter bestehender Worker lädt sieben Historienseiten und passende öffentliche Futuresdaten', calls.filter(c => c.path.endsWith('history-candles')).length === 7 && calls.every(c => c.method === 'GET' && c.symbol === 'BTCUSDT' && c.path.startsWith('/api/v2/mix/market/') && c.params.productType === 'USDT-FUTURES' && !Object.keys(c.headers).some(k => /access-key|access-sign|authorization/i.test(k))));
    check('Tatsächliche Range L97/U103, ATR2 und vollständige 14 Tage', await page.evaluate(() => { const g = __g12.view.state.confirmed.run.grid; return g.plan.range.lower === 97 && g.plan.range.upper === 103 && g.plan.range.atr === 2 && g.market.coverage.candles === 1344 && g.market.coverage.pages === 7; }));
    check('Karte trennt Limitpläne von Ausführung; Ziele bedingt, kein fingiertes Netto', await page.evaluate(() => { const g = __g12.view.state.confirmed.run.grid, box = document.getElementById('bot-grid-summary'); return g.plan.orders.length > 1 && g.plan.orders.every(o => o.status === 'planned' && o.side === 'buy') && g.plan.contingent.every(o => o.reduceOnly && o.status === 'conditional-after-confirmed-fill') && /keine liegenden Börsenorders/.test(box.textContent) && box.querySelectorAll('dl>div').length === 8 && __g12.view.state.confirmed.run.netUSDT === '0'; }));
    await page.locator('#bot-grid-summary details>summary').click(); check('Limitpläne auf- und zuklappbar mit Preis/Menge und Ziel nach Fill', await page.evaluate(() => { const d = document.querySelector('#bot-grid-summary details'); return d.open && /Kauf-Limit/.test(d.textContent) && /Ziel nach Fill/.test(d.textContent); }));
    const original = await page.evaluate(() => JSON.stringify(__g12.view.state.confirmed.run.grid));
    apiError = 'offline'; await page.click('#bot-grid-check'); await page.waitForFunction(() => !__g12.view.state.busy);
    check('Netzfehler erhält letzten bestätigten Plan ohne neue Freigabe', await page.evaluate(original => JSON.stringify(__g12.view.state.confirmed.run.grid) === original && /fehlgeschlagen|nicht verfügbar|fetch|network/i.test(document.getElementById('bot-status').textContent), original));
    apiError = '429'; const before429 = calls.length; await page.click('#bot-grid-check'); await page.waitForFunction(() => !__g12.view.state.busy); await page.click('#bot-grid-check'); await page.waitForFunction(() => !__g12.view.state.busy);
    check('429-Abstand im tatsächlichen Worker verhindert sofortigen Wiederabruf', calls.length === before429 + 1 && await page.evaluate(original => JSON.stringify(__g12.view.state.confirmed.run.grid) === original && /gedrosselt|Pause/.test(document.getElementById('bot-status').textContent), original)); apiError = null;
    await page.fill('#bot-gridCapital', '90'); await page.click('#bot-load'); await page.waitForFunction(() => !__g12.view.state.busy);
    check('Statusladen erhält Grid-Entwurf, bestätigter Lauf bleibt bei 80 USDT', await page.inputValue('#bot-gridCapital') === '90' && await page.evaluate(() => __g12.view.state.confirmed.settings.grid.capitalUSDT === '80'));
    await page.reload(); await page.waitForFunction(() => window.__g12?.view.state.confirmed?.run?.grid && !__g12.view.state.busy); await page.click('#ki-bot-tab'); await page.waitForFunction(() => !__g12.view.state.busy);
    check('Reload stellt bestätigte Grid-Felder, eigenes Long-Original und Plan wieder her', await page.inputValue('#bot-gridCapital') === '80' && await page.inputValue('#bot-strategy') === 'adaptive-grid' && await page.evaluate(original => JSON.stringify(__g12.view.state.confirmed.run.grid) === original && __g12.view.state.confirmed.logs.filter(x => x.type === 'start').length === 1, original));
    const archive = await page.evaluate(async () => { const original = await __g13.exportModelArchive(), restored = __g13.validateModelArchive(original); return { same: JSON.stringify(original.bot.run.grid) === JSON.stringify(restored.bot.run.grid), disabled: !restored.bot.enabled, sourceEnabled: original.bot.enabled, model: restored.bot.run.grid.modelVersion }; });
    check('Echter Archivexport/-import erhält Grid-Originale und reaktiviert den Bot nicht', archive.same && archive.disabled && archive.sourceEnabled && archive.model === 'adaptive-grid-1');
    await page.evaluate(() => { document.getElementById('bot-grid-settings').open = true; document.querySelector('#bot-grid-settings details').open = true; });
    for (const width of [320, 390, 768, 1440]) { await page.setViewportSize({ width, height: 844 }); for (const layout of ['standard', 'dashboard']) { await page.evaluate(layout => document.querySelector(`[data-presentation-set="${layout}"]`).click(), layout); await page.waitForTimeout(100);
      const g = await page.evaluate(() => { const root = document.getElementById('bot-view'), box = root.getBoundingClientRect(), nodes = [...root.querySelectorAll('input:not([type=checkbox]),select,button,summary')].filter(n => n.getClientRects().length); return { overflow: document.documentElement.scrollWidth > innerWidth + 1 || root.scrollWidth > root.clientWidth + 1, escaped: nodes.filter(n => n.getBoundingClientRect().right > Math.min(box.right, innerWidth) + 1).map(n => n.id), touch: nodes.every(n => n.getBoundingClientRect().height >= 44) }; });
      check(width + 'px/' + layout + ': Grid-Felder und Pläne im Rahmen mit 44px Tippflächen', !g.overflow && !g.escaped.length && g.touch, JSON.stringify(g)); }
    }
    for (const entry of await page.evaluate(() => __sdAppearance.palette)) { await page.evaluate(color => document.querySelector(`[data-background-color="${color}"]`).click(), entry.color);
      check(entry.name + ': Grid-Texte/Status auf Flächen mit AA-Kontrast', await page.evaluate(() => { const cs = getComputedStyle(document.documentElement), v = k => cs.getPropertyValue('--' + k).trim(); return ['surface', 'surface-2', 'field'].every(bg => ['text', 'muted', 'up-text', 'down-text'].every(fg => __sdAppearance.contrast(v(fg), v(bg)) >= 4.5)); }));
    }
    const age = await page.evaluate(() => Date.now() - __g12.view.state.confirmed.run.grid.market.asOf); if (age <= 30000) await page.waitForTimeout(30001 - age);
    check('Gespeicherte alte Prüfung zeigt „neu prüfen“ und bleibt keine aktuelle Grid-Freigabe', /neu prüfen/.test(await page.textContent('#bot-grid-summary')));
    const callCount = calls.length; await page.waitForTimeout(250); check('Keine zusätzliche automatische Grid-Abfrage oder fingierte Fills im Hintergrund', calls.length === callCount && await page.evaluate(() => __g12.view.state.confirmed.run.grid.inventory.quantity === '0'));
    await page.setViewportSize({ width: 390, height: 844 }); await page.evaluate(() => document.querySelector('[data-theme-set=light]').click()); await page.locator('#bot-grid-summary').screenshot({ path: '/tmp/scalpdesk-357-grid-mobile.png' });
    await page.locator('#bot-scenario>summary').click(); await page.click('#bot-zero-values'); await page.fill('#bot-value-realized', '10'); await page.click('#bot-step'); await page.waitForFunction(() => !__g12.view.state.busy && __g12.view.state.confirmed.run.stops.gain);
    check('Bestehender Gewinnschutz entzieht auch gespeichertem Grid sofort die Einstiegsanzeige', /Laufschutz sperrt/.test(await page.textContent('#bot-grid-summary')) && await page.evaluate(() => !__g12.view.state.confirmed.actions.entries));
    await page.click('#bot-grid-check'); await page.waitForFunction(() => !__g12.view.state.busy); check('Neuer Grid-Plan respektiert Grenzsperre, keine Kaufabsichten', await page.evaluate(() => __g12.view.state.confirmed.run.grid.plan.orders.length === 0 && __g12.view.state.confirmed.run.grid.plan.keepExistingProtection));
    await page.click('#bot-pause'); await page.waitForFunction(() => !__g12.view.state.busy); check('Bot-Pause sperrt Grid-Prüfung und erhält gespeicherte Pläne/Schutz', await page.isDisabled('#bot-grid-check') && await page.evaluate(() => !__g12.view.state.confirmed.enabled && __g12.view.state.confirmed.run.grid.plan.keepExistingProtection));
    check('Keine JavaScript-Fehler oder privaten Markt-/Orderaufrufe', !errors.length && calls.every(c => c.path.startsWith('/api/v2/mix/market/')), errors.join('; '));
    const oldCtx = await browser.newContext({ serviceWorkers: 'block' }); await oldCtx.route(h.URL_BASE + '/grid-fixture.html', route => route.fulfill({ contentType: 'text/html', body: '<!doctype html><div id="host"></div><div id="global"></div>' }));
    const oldPage = await oldCtx.newPage(); oldPage.on('pageerror', e => errors.push(e.message)); await oldPage.goto(h.URL_BASE + '/grid-fixture.html');
    await oldPage.evaluate(async () => { const { createBotView } = await import('/shared/bot-view.mjs'); window.oldGridCommands = 0; const view = createBotView({ host: document.getElementById('host'), globalHost: document.getElementById('global'), load: async () => ({ revision: 0, enabled: false, run: null, actions: {} }), command: async () => { window.oldGridCommands++; throw new Error('Alter Dienst darf keinen Grid-Start erhalten'); }, currentSymbol: () => 'BTCUSDT', fxReference: () => null, changed: () => {}, exportState: async () => '{}', destination: 'oracle' }); await view.refresh(); });
    await oldPage.selectOption('#bot-strategy', 'adaptive-grid'); await oldPage.click('#bot-preset'); await oldPage.click('#bot-start');
    check('Alter Oracle-Dienst: verständliche Aktualisierung statt unpassendem Grid-Auftrag', await oldPage.evaluate(() => window.oldGridCommands === 0 && /auf 2.11.0 aktualisieren oder lokal simulieren/.test(document.getElementById('bot-status').textContent)));
    check('Auch alte Dienstanzeige ohne JavaScript-Absturz', !errors.length, errors.join('; ')); await oldCtx.close();
    await ctx.close(); console.log(`${pass}/${pass + fail} bestanden`); process.exitCode = fail ? 1 : 0;
  } catch (e) { console.error('Abbruch', e); process.exitCode = 1; } finally { await browser?.close(); await h.teardown(); }
})();
