// 3.58.0: Restzeit an laufenden Kerzen und lesbare Auswertungen mit großen Originalwerten.
const h = require('./harness'); let pass = 0, fail = 0;
const check = (name, ok, detail = '') => { ok ? pass++ : fail++; console.log(`${ok ? '✓' : '✗'} ${name}${detail ? ' — ' + detail : ''}`); };
(async () => { let browser;
  try {
    await h.setup(); await h.ctl('/walk?on=0'); browser = await h.launch();
    const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, timezoneId: 'Europe/Berlin' }), page = await ctx.newPage(), errors = [];
    page.on('pageerror', e => errors.push(e.message)); const at = Date.now() - 3 * 86400000;
    const trade = (id, symbol, net, index, reasons) => ({ id, symbol, side: 'long', mode: 'isolated', entry: 1000000000, exit: 1000000000 + net, leverage: 10, qty: 1, margin: 100000000, openedAt: at + index * 86400000 - 3600000, closedAt: at + index * 86400000, source: 'spot', sl: 999999999, tp: null, ack: { sl: false, tp: false }, preRealized: 0, fees: 0, pnl: net, pnlSource: 'calc', fx: .92, reasons, r0: { entry: 1000000000, sl: 999999999, qty: 1, at: at + index * 86400000 - 3600000 } });
    const fixtures = [trade('UI-A', 'BTCUSDT', 123456789.12, 0, ['EMA-20/50-Trend', 'RSI']), trade('UI-B', 'ETHUSDT', -12345678.11, 1, ['Funding']), trade('UI-C', 'LANGERCOINNAMEUSDT', 987654321.45, 2, ['Doppelboden', 'News'])];
    await ctx.addInitScript(rows => { if (!localStorage.getItem('ui82seed')) { localStorage.setItem('ui82seed', '1'); localStorage.setItem('scalpdesk.history.v1', JSON.stringify(rows)); } }, fixtures);
    await page.goto(h.URL_BASE + '/weather-widget-v2.html'); await page.waitForFunction(() => window.__pdf1?.view.state.series['1m'].length >= 5 && __pdf1.view.state.series['1h'].length >= 5);
    await page.waitForFunction(() => [...document.querySelectorAll('.of-row[data-running="true"] .of-row-countdown')].length === 2);
    check('Minuten- und Stundenrestzeit direkt in den zwei aktuellen Karten', await page.evaluate(() => [...document.querySelectorAll('.of-block')].every(block => { const row = block.querySelector('.of-row[data-running="true"]'), timer = row.querySelector('.of-row-countdown'); return row.querySelector('.of-time>span').textContent === 'jetzt' && !timer.hidden && /^\d\d:\d\d$/.test(timer.textContent) && block.querySelector('.of-countdown').textContent === 'Rest ' + timer.textContent && /Restlaufzeit/.test(timer.getAttribute('aria-label')); })));
    check('Acht abgeschlossene Karten zeigen keine verbleibende Zeit', await page.evaluate(() => { const timers = [...document.querySelectorAll('.of-row[data-running="false"] .of-row-countdown')]; return timers.length === 8 && timers.every(n => n.hidden && !n.textContent && getComputedStyle(n).display === 'none'); }));
    const beforeTimer = await page.evaluate(() => { window.ui82Rows = [...document.querySelectorAll('.of-row:not(.of-legend)')]; window.ui82Heights = ui82Rows.map(n => n.getBoundingClientRect().height); return document.querySelector('.of-block[data-interval="1m"] .of-row[data-running="true"] .of-row-countdown').textContent; });
    await page.waitForFunction(old => document.querySelector('.of-block[data-interval="1m"] .of-row[data-running="true"] .of-row-countdown').textContent !== old, beforeTimer);
    check('Sekundentakt verändert den Timer ohne neue Kerzenknoten oder Höhensprung', await page.evaluate(() => { const rows = [...document.querySelectorAll('.of-row:not(.of-legend)')]; return rows.every((n, i) => n === ui82Rows[i] && Math.abs(n.getBoundingClientRect().height - ui82Heights[i]) < 1); }));
    await page.click('#tabbar [data-tab="pos"]'); await page.evaluate(() => document.getElementById('analysis').open = true); await page.waitForFunction(() => document.querySelectorAll('#breakdowns .bd').length === 6 && document.querySelector('#monthly .mo-row.total'));
    const originals = await page.evaluate(() => JSON.stringify({ positions: __g05.state.positions, trades: __g05.state.trades, movements: __g05.state.movements }));
    const figures = await page.evaluate(() => JSON.stringify({ tables: [...document.querySelectorAll('#breakdowns .bd')].map(n => n.textContent), monthly: document.getElementById('monthly').textContent }));
    check('Alle sechs Auswertungen und die Monatsübersicht vollständig vorhanden', await page.evaluate(() => [...document.querySelectorAll('#breakdowns .bd h4')].map(n => n.textContent).join('|') === 'Nach Grund|Nach Bereich der Gründe|Nach Coin|Long / Short|Einstiegszeit|Haltedauer' && document.querySelectorAll('#monthly .mo-row:not(.head)>span').length >= 12));
    check('Kleine Stichproben klar vorläufig markiert und ohne gedämpfte Zahlen', await page.evaluate(() => document.querySelectorAll('#breakdowns .bd-row.thin').length > 0 && [...document.querySelectorAll('#breakdowns .bd-row.thin')].every(n => getComputedStyle(n.firstElementChild, '::after').content.includes('vorläufig') && getComputedStyle(n.children[3]).opacity === '1')));
    for (const layout of ['standard', 'dashboard']) {
      await page.evaluate(layout => document.querySelector(`[data-presentation-set="${layout}"]`).click(), layout);
      for (const width of [320, 390, 768, 1440]) {
        await page.setViewportSize({ width, height: 1000 }); await page.waitForTimeout(180);
        const result = await page.evaluate(() => { const nodes = [...document.querySelectorAll('#breakdowns .bd,#breakdowns .bd-row,#breakdowns .bd-row>span,#breakdowns .bd-bar b,#monthly,#monthly .mo-row,#monthly .mo-row>span')].filter(n => n.getClientRects().length); const bad = nodes.filter(n => n.scrollWidth > n.clientWidth + 1).map(n => n.className + ': ' + n.scrollWidth + '/' + n.clientWidth); return { side: document.documentElement.scrollWidth > innerWidth + 1, bad: bad.slice(0, 8) }; });
        check(`${layout}/${width}px: sämtliche Auswertungszahlen ohne Überlauf`, !result.side && result.bad.length === 0, JSON.stringify(result));
        check(`${layout}/${width}px: Netto, Treffer, R und Monatswerte unverändert`, await page.evaluate(raw => JSON.stringify({ tables: [...document.querySelectorAll('#breakdowns .bd')].map(n => n.textContent), monthly: document.getElementById('monthly').textContent }) === raw, figures));
        if (width <= 390) check(`${layout}/${width}px: Werte beschriftet statt schmaler Tabellenzeile`, await page.evaluate(() => { const row = document.querySelector('#breakdowns .bd-row:not(.head)'), monthly = document.querySelector('#monthly .mo-row:not(.head)'); return getComputedStyle(row.parentElement.querySelector('.head')).display === 'none' && ['Trades', 'Trefferquote', 'Ø R', 'Netto USDT (Ø je Trade)'].every((name, i) => getComputedStyle(row.children[i + 1], '::before').content.includes(name)) && getComputedStyle(monthly.children[3], '::before').content.includes('Netto USDT'); }));
      }
      for (const entry of await page.evaluate(() => __sdAppearance.palette)) {
        await page.evaluate(color => document.querySelector(`[data-background-color="${color}"]`).click(), entry.color);
        check(`${layout}/${entry.name}: Zahlen und Beschriftungen mit AA-Kontrast`, await page.evaluate(() => { const s = getComputedStyle(document.documentElement), v = k => s.getPropertyValue('--' + k).trim(); return ['text', 'muted', 'up-text', 'down-text'].every(k => __sdAppearance.contrast(v(k), v('surface-2')) >= 4.5) && [...document.querySelectorAll('#breakdowns .bd-row.thin>span')].every(n => getComputedStyle(n).opacity === '1'); }));
      }
    }
    check('Originalpositionen, abgeschlossene Trades und Geldbewegungen erhalten', await page.evaluate(raw => JSON.stringify({ positions: __g05.state.positions, trades: __g05.state.trades, movements: __g05.state.movements }) === raw, originals));
    await page.setViewportSize({ width: 390, height: 844 }); await page.evaluate(() => { document.querySelector('[data-presentation-set="standard"]').click(); document.querySelector('[data-theme-set="light"]').click(); }); await page.waitForTimeout(200);
    await page.locator('#breakdowns .bd').first().screenshot({ path: '/tmp/scalpdesk-358-auswertung-mobile.png' }); await page.locator('#monthly').screenshot({ path: '/tmp/scalpdesk-358-monate-mobile.png' });
    await page.click('#tabbar [data-tab="chart"]'); await page.locator('.of-block[data-interval="1m"] .of-row[data-running="true"]').screenshot({ path: '/tmp/scalpdesk-358-restzeit.png' });
    // UTC-Schlusswechsel kontrolliert am echten View-Vertrag, ohne die Uhr oder Originaldaten der App zu verändern.
    const rollover = await page.evaluate(async () => { const { createOrderflowView } = await import('/shared/orderflow-view.mjs'); const root = document.createElement('div'); document.body.append(root); let now = Math.floor(Date.now() / 3600000) * 3600000 + 3599000; const view = createOrderflowView({ root, context: () => ({ symbol: 'BTCUSDT', paused: true, connected: false }), now: () => now, fetchRows: async () => [], readPrefs: () => null, savePrefs: () => {}, streamsChanged: () => {} }); view.sync(); const read = () => [...root.querySelectorAll('.of-row[data-running="true"] .of-row-countdown')].map(n => n.textContent); const before = read(); now += 1000; view.tick(); const after = read(); root.remove(); return { before, after }; });
    check('UTC-Minuten-/Stundenschluss setzt Karten-Timer auf 01:00/60:00 zurück', rollover.before.join('|') === '00:01|00:01' && rollover.after.join('|') === '01:00|60:00', JSON.stringify(rollover));
    await page.reload(); await page.click('#tabbar [data-tab="pos"]'); await page.evaluate(() => document.getElementById('analysis').open = true); await page.waitForFunction(() => document.querySelectorAll('#breakdowns .bd').length === 6);
    check('Reload erhält Auswertungswerte und Originalbücher', await page.evaluate(({ raw, values }) => JSON.stringify({ positions: __g05.state.positions, trades: __g05.state.trades, movements: __g05.state.movements }) === raw && JSON.stringify({ tables: [...document.querySelectorAll('#breakdowns .bd')].map(n => n.textContent), monthly: document.getElementById('monthly').textContent }) === values, { raw: originals, values: figures }));
    check('Keine JavaScript-Laufzeitfehler', errors.length === 0, errors.join(' | ')); await ctx.close(); console.log(`${pass}/${pass + fail} bestanden`); process.exitCode = fail ? 1 : 0;
  } catch (e) { console.error('Abbruch', e); process.exitCode = 1; } finally { if (browser) await browser.close(); await h.teardown(); }
})();
