// 3.61.0: wirklicher öffentlicher Demo-Worker, native IDB, Live-Ausführung und echte UI-Klicks.
const h=require('./harness'),fs=require('fs');let pass=0,fail=0;
const check=(name,ok,detail='')=>{ok?pass++:fail++;console.log(`${ok?'✓':'✗'} ${name}${detail?' — '+JSON.stringify(detail).slice(0,1000):''}`);};
(async()=>{let browser;try{
 const f=await import('./fixtures/confluence-live.mjs');await h.setup();await h.ctl('/walk?on=0');browser=await h.launch({workspace:'fresh'});const ctx=await browser.newContext({viewport:{width:390,height:844},acceptDownloads:true}),page=await ctx.newPage(),errors=[],calls=[];page.on('pageerror',e=>errors.push(e.message));
 await ctx.addInitScript(()=>{localStorage.setItem('scalpdesk.ki.settings.v1',JSON.stringify({patternWeight:0}));if(!localStorage.getItem('paper85seed')){localStorage.setItem('paper85seed','1');localStorage.setItem('scalpdesk.watchlist.v1',JSON.stringify(['BTC','ETH','LTC']));const at=Date.now()-86400000,pos={id:'PAPER85-PERSOENLICH',symbol:'LTCUSDT',side:'long',mode:'isolated',entry:100,leverage:5,qty:1,margin:20,openedAt:at,source:'spot',liqExchange:null,preRealized:0,sl:90,tp:150,ack:{sl:false,tp:false}};localStorage.setItem('scalpdesk.positions.v1',JSON.stringify([pos]));localStorage.setItem('scalpdesk.history.v1',JSON.stringify([{...pos,id:'PAPER85-ABGESCHLOSSEN',exit:110,closedAt:at+3600000,fees:1,pnl:9,pnlSource:'calc'}]));}});
 const origin=Date.now(),prices={BTCUSDT:124,ETHUSDT:12.4,LTCUSDT:1.24};
 await ctx.route('https://api.bitget.com/**',async route=>{const req=route.request(),u=new URL(req.url()),symbol=u.searchParams.get('symbol'),scale=symbol==='ETHUSDT'?.1:symbol==='LTCUSDT'?.01:1;calls.push({path:u.pathname,symbol,method:req.method()});const body=f.liveBitgetResponse(req.url(),Date.now(),origin);
  if(u.pathname.endsWith('/ticker'))body.data=[{symbol,bidPr:String(prices[symbol]-.01*scale),askPr:String(prices[symbol]),markPrice:String(prices[symbol]),ts:String(Date.now())}];
  else if(u.pathname.endsWith('/history-candles'))body.data=body.data.map(row=>row.map((x,i)=>i>=1&&i<=4?String(Number(x)*scale):x));
  else if(u.pathname.endsWith('/contracts')){body.data[0].pricePlace=String(scale<1?3:1);body.data[0].priceEndStep='5';}
  await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(body)});
 });
 await page.goto(h.URL_BASE+'/weather-widget-v2.html');await page.waitForFunction(()=>window.__paper&&window.__g12?.view.state.confirmed);await page.click('#workspace-bot');
 check('Frische App: Demo aus, keine öffentlichen/private Bitget-Abfragen',await page.evaluate(()=>!__paper.controller.state.active&&!__paper.controller.state.book.run)&&!calls.length);
 check('Einrichtung und alte manuelle Modellprüfung zunächst zugeklappt',await page.evaluate(()=>!document.getElementById('paper-settings').open&&!document.getElementById('bot-model-check').open));
 await page.click('#paper-start');check('Ohne eigene Geldfelder kein Lauf; Einrichtung wird erreichbar geöffnet',await page.evaluate(()=>!__paper.controller.state.book.run&&document.getElementById('paper-settings').open));
 await page.click('#bot-preset');await page.fill('#bot-leverage','5');await page.selectOption('#paper-setting-anchorPolicy','nearest');await page.fill('#paper-setting-slippageBps','0');
 const original=await page.evaluate(()=>JSON.stringify([__g05.state.positions,__g05.state.trades,__g05.state.demoPositions,__g05.state.demoTrades,__g05.state.alarms]));
 await page.click('#paper-start');try{await page.waitForFunction(()=>__paper.controller.state.book.run?.positions.length===1,null,{timeout:60000});}catch(e){console.log('DEMO-Diagnose',await page.evaluate(()=>({book:__paper.controller.state.book,message:__paper.controller.state.message,error:__paper.controller.state.error,modelError:__paper.controller.state.modelError})),calls);throw e;}
 const p=await page.evaluate(()=>__paper.controller.state.book.run.positions[0]);
 check('Tatsächlicher Konfluenz-Worker eröffnet BTC-Papiertrade auf eigener IDB',p.instrument==='BTCUSDT'&&p.strategy==='confluence'&&p.entry===124&&await page.evaluate(async()=> (await __paper.read()).run.positions.length===1));
 check('Grün bedeutet aktiven Executor mit aktuellen passenden Kursen',await page.locator('#paper-status').evaluate(n=>n.textContent==='Demo läuft'&&n.classList.contains('ki-positive')));
 check('Einrichtung nach erfolgreichem Start zugeklappt, Live-Position bleibt im Mittelpunkt',await page.evaluate(()=>!document.getElementById('paper-settings').open));
 check('Livekarte nennt Coin, Richtung, eigene Menge, Stop und Ziel eindeutig',/BTC\/USDT.*Long/.test(await page.textContent('#paper-positions'))&&await page.locator('#paper-positions dt').count()===8);
 await page.evaluate(()=>window.paper85Card=document.querySelector('[data-paper-position]'));prices.BTCUSDT=p.entry+(p.tp-p.entry)*.2;
 await page.waitForFunction(()=>Number(__paper.controller.state.quote?.bid)>__paper.controller.state.book.run.positions[0].entry);
 check('Live-PnL steigt, gleiche Karte bleibt erhalten',await page.evaluate(()=>paper85Card===document.querySelector('[data-paper-position]')&&document.querySelector('.paper-position .bot-net-positive')));
 const second=await ctx.newPage();second.on('pageerror',e=>errors.push(e.message));await second.goto(h.URL_BASE+'/weather-widget-v2.html');await second.waitForFunction(()=>window.__paper?.controller.state.book.run);await second.click('#workspace-bot');await second.click('#paper-resume');await second.waitForFunction(()=>!__paper.controller.state.busy&&!!(__paper.controller.state.error||__paper.controller.state.active));
 const secondState=await second.evaluate(()=>({active:__paper.controller.state.active,error:__paper.controller.state.error,message:__paper.controller.state.message}));
 check('Zweiter Tab startet keinen zweiten Executor und keinen zweiten Trade',!secondState.active&&/anderen Tab/.test(secondState.error)&&await page.evaluate(()=>__paper.controller.state.book.run.positions.length===1),secondState);await second.close();
 prices.BTCUSDT=p.tp+1;await page.waitForFunction(()=>__paper.controller.state.book.closed.length===1,null,{timeout:15000});
 check('Kursziel erzeugt sichtbaren echten Demo-Abschluss',await page.evaluate(()=>__paper.controller.state.book.closed[0].reason==='Ziel erreicht'&&!__paper.controller.state.book.run.positions.length)&&/Demo-Abschlüsse \(1\)/.test(await page.textContent('#paper-history')));
 check('Neue Demo-Trades sind nicht in persönlicher Sicherung',await page.evaluate(id=>!JSON.stringify(__g05.backupPayload()).includes(id),p.id));
 await page.click('[data-workspace-target="chart"]');await page.locator('#watchlist [data-watch="ETH"]').click();await page.waitForFunction(()=>__g05.state.symbol==='ETHUSDT');await page.click('#workspace-bot');
 check('Coinwechsel: Auswahl ETH, bisheriger Lauf eindeutig BTC',/Auswahl: ETH\/USDT · Lauf: BTC\/USDT/.test(await page.textContent('#paper-context'))&&await page.evaluate(()=>__paper.controller.state.book.run.instrument==='BTCUSDT'));
 check('Roter Beenden-Knopf, Löschung während aktiver Demo gesperrt',await page.locator('#paper-stop').evaluate(n=>n.classList.contains('paper-stop'))&&await page.locator('#paper-clear').isDisabled());
 await page.click('#paper-stop');await page.waitForFunction(()=>!__paper.controller.state.busy&&__paper.controller.state.book.run.status==='ended');check('Beenden hält Executor und neue Trades an',await page.evaluate(()=>!__paper.controller.state.active&&!__paper.controller.state.book.run.orders.length));
 prices.BTCUSDT=124;await page.click('#paper-start');try{await page.waitForFunction(()=>__paper.controller.state.book.run?.instrument==='ETHUSDT'&&__paper.controller.state.book.run.positions.length===1,null,{timeout:60000});}catch(e){console.log('ETH-Diagnose',await page.evaluate(()=>({book:__paper.controller.state.book,message:__paper.controller.state.message,error:__paper.controller.state.error,modelError:__paper.controller.state.modelError})),calls.slice(-16));throw e;}
 check('Neuer Lauf übernimmt tatsächliche Vorauswahl ETH statt LTC/BTC',await page.evaluate(()=>__paper.controller.state.book.run.positions[0].instrument==='ETHUSDT'&&__paper.controller.state.book.run.positions[0].entry===12.4));
 for(const width of[320,390,768,1440]){await page.setViewportSize({width,height:844});check(width+'px: Demo ohne Text-/Seitenüberlauf',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1&&[...document.querySelectorAll('#paper-demo dd')].every(n=>n.getBoundingClientRect().right<=innerWidth+1)));if(width===320||width===390)await page.locator('#paper-demo').screenshot({path:'/tmp/scalpdesk-paper-'+width+'.png'});}
 await page.reload();await page.waitForFunction(()=>window.__paper?.controller.state.book.run);await page.click('#workspace-bot');
 check('Reload startet nicht automatisch; gleiche echte Demo-Position bleibt gespeichert',await page.evaluate(()=>!__paper.controller.state.active&&__paper.controller.state.book.run.positions.length===1&&__paper.controller.state.book.run.instrument==='ETHUSDT'));
 await page.click('#paper-stop');await page.waitForFunction(()=>!__paper.controller.state.busy&&__paper.controller.state.book.run.status==='ended');
 check('Frischer Stop schließt verbliebene eigene Demo-Position',await page.evaluate(()=>__paper.controller.state.book.run.positions.length===0&&__paper.controller.state.book.closed.length===2));
 await page.click('#paper-clear');check('Löschung erst nach bewusstem Demo-Hinweis',await page.locator('#paper-delete-confirm').isVisible()&&await page.evaluate(()=>__paper.controller.state.book.closed.length===2));await page.click('#paper-delete-yes');await page.waitForFunction(()=>!__paper.controller.state.book.run&&!__paper.controller.state.busy);
 check('Löschung dauerhaft nur im eigenen Demo-Buch',await page.evaluate(async()=>!(await __paper.read()).run&&(await __paper.read()).closed.length===0));
 check('Persönliche Positionen/Trades/Alarme und alte Demo-Bücher unverändert',await page.evaluate(raw=>JSON.stringify([__g05.state.positions,__g05.state.trades,__g05.state.demoPositions,__g05.state.demoTrades,__g05.state.alarms])===raw,original));
 check('Nur öffentliche Markt-GETs, keine Order-/Kontoaufrufe',calls.length>0&&calls.every(x=>x.method==='GET'&&x.path.startsWith('/api/v2/mix/market/')),calls.slice(0,8));
 check('Keine JavaScript-Fehler',!errors.length,errors);
 }finally{await browser?.close();await h.teardown();}console.log(`${pass}/${pass+fail} bestanden`);process.exitCode=fail?1:0;
})().catch(e=>{console.error(e);process.exitCode=1;});
