// G11: fachliche feste Kerzen, Zeit-/Ereignisreihenfolge und ursprüngliche Risikogrenzen.
let pass = 0, fail = 0;
const check = (name, ok) => { ok ? pass++ : fail++; console.log(`${ok ? '✓' : '✗'} ${name}`); };
const throws = fn => { try { fn(); return false; } catch { return true; } };
(async () => {
  const P = await import('../shared/po3-core.mjs'), S = await import('../shared/po3-simulator.mjs');
  const M = 60e3, at = Date.UTC(2026, 9, 7, 12), c = (i, open = 100, high = 101, low = 99, close = 100, step = M) => ({ time: at + i * step, end: at + (i + 1) * step, knownAt: at + (i + 1) * step, open, high, low, close, volume: 100 });
  const cfg = { closure: 'tp1' }, p = P.po3Settings(cfg), box = { high: 104, low: 100, height: 4, from: at, to: at + 6 * M }, sweep = { extreme: 99, time: at, at: at + M };
  check('Hierarchie, gleiche Ebenen erlaubt und 4h-Kontext optional', throws(() => P.po3Settings({ bias: '5m', setup: '1h' })) && P.po3Settings({ contextOn: false, context: '1m' }).contextOn === false && P.po3Settings({ bias: '5m', setup: '5m' }).bias === '5m');
  check('UTC-Heute und exklusive eigene Endgrenze ohne Zukunft', P.po3Window('today', at).from === Date.UTC(2026, 9, 7) && P.po3Window('custom', at, { from: at - M, to: at }).exclusive && throws(() => P.po3Window('custom', at, { from: at, to: at + M })));
  const before = Array.from({ length: 6 }, (_, i) => c(i, 100.5, 101, 100, 100.6));
  const A = P.accumulation(before, 1); check('Box aus mindestens sechs vorherigen Kerzen, Sweep nicht eingerechnet', A?.height === 1 && !P.accumulation(before.slice(1), 1) && !P.accumulation(before, .5));
  const down = P.manipulation(A, c(6, 100.4, 100.8, 99.5, 100.4)), up = P.manipulation(A, c(6, 100.4, 101.5, 100.2, 100.4));
  check('Long-/Short-Sweep spiegelbildlich mit Rückschluss in Box, Box eingefroren', down?.direction === 1 && up?.direction === -1 && down.box.high === A.high && down.extreme === 99.5);
  check('Beide Boxseiten gesweept: mehrdeutig; Schluss außerhalb: kein Setup', P.manipulation(A, c(6, 100.4, 101.5, 99.5, 100.4)).ambiguous && !P.manipulation(A, c(6, 100.4, 100.8, 99.5, 99.8)));
  const three = [c(0, 100, 101, 99, 100), c(1, 101, 103, 100, 102), c(2, 103, 104, 102, 103)], zone = P.po3Fvg(three, { timeframe: '1m', atr: 2, instrument: 'BTCUSDT' });
  check('Bullishes FVG, Alarmgröße ≥ 0,5 ATR und Bestätigung nach dritter Kerze', zone.direction === 1 && zone.low === 101 && zone.high === 102 && zone.alarmEligible && zone.confirmedAt === at + 3 * M);
  check('FVG nach Sweep verlangt drei danach liegende Kerzen', !P.po3Fvg(three, { timeframe: '1m', atr: 2, instrument: 'BTCUSDT', after: at + M }));
  check('Retest erst ab Folgekerze, kein rückwirkender Retest der Bestätigung', !P.po3Retest(zone, three[2]) && P.po3Retest(zone, c(3, 102, 103, 101.5, 102)));
  check('Vollständig gefülltes FVG bleibt kein aktives Alarm-FVG', P.fvgState(zone, [c(3, 102, 103, 101, 102)]).filledAt === at + 4 * M);
  const z2 = { ...zone, id: 'higher', timeframe: '1h', low: 101.5, high: 103 }, touching = { ...z2, low: 102, high: 103 };
  check('Überlappung aus verschiedenen Ebenen gleicher Richtung mit echter Breite', P.fvgOverlaps([zone, z2], ['1m', '1h'])[0].low === 101.5 && !P.fvgOverlaps([zone, touching], ['1m', '1h']).length && !P.fvgOverlaps([zone, { ...z2, direction: -1 }], ['1m', '1h']).length);
  const mandatory = { direction: 1, sweep: true, retest: true, bias: 1, impulse: true, volume: true, rsi: true, funding: true };
  const unknown = P.po3Score(mandatory, cfg);
  check('Unbestimmte Kriterien ehrlich 0, Kontext AUS bleibt Nenner 80', unknown.score === 81.25 && unknown.denominator === 80 && unknown.unknown.length === 3 && unknown.points.volume === 0);
  check('PO3 maximal 100, keine zusätzlichen G10-Musterpunkte', P.po3Score({ ...mandatory, contextBias: 1, contextFvg: true }, { ...cfg, criteria: 'g10', contextOn: true }).score === 100);
  check('Bias ist Punktkriterium, keine erfundene Gegen-Trend-Sperre', P.po3Score({ ...mandatory, bias: -1, contextBias: 1, contextFvg: true }, { ...cfg, criteria: 'g10', contextOn: true }).eligible);
  check('Sweep/Retest/Impuls zwingend trotz sonstiger Punkte', !P.po3Score({ ...mandatory, sweep: false }, { ...cfg, criteria: 'g10' }).eligible && !P.po3Score({ ...mandatory, retest: false }, { ...cfg, criteria: 'g10' }).eligible);
  const levels = P.po3Levels({ candle: c(9, 100, 100.5, 99.8, 100), direction: 1, sweep, setupSweep: sweep, entryATR: 1, setupATR: 2, box, tickSize: .1 }, cfg);
  check('Stop hinter Entry-Sweep mit 0,1 ATR und TP1 ≥2R, TP2/TP3 geordnet', levels.status === 'bereit' && levels.sl === 98.9 && levels.rewardRisk >= 2 && levels.tps[1] === 104 && levels.tps[2] === 108);
  check('TP-Geometrie ablehnen statt falsch sortierte Ziele anzeigen', P.po3Levels({ candle: c(9), direction: 1, sweep, setupSweep: sweep, entryATR: 1, setupATR: 2, box: { ...box, high: 101 }, tickSize: .1 }, cfg).status === 'abgelehnt');
  check('Nähere Kontextzone kappt TP3; Zone vor TP2 lehnt ab', P.po3Levels({ candle: c(9), direction: 1, sweep, setupSweep: sweep, entryATR: 1, setupATR: 2, box, tickSize: .1, contextLevels: [{ price: 106 }] }, cfg).tps[2] === 106 && P.po3Levels({ candle: c(9), direction: 1, sweep, setupSweep: sweep, entryATR: 1, setupATR: 2, box, tickSize: .1, contextLevels: [{ price: 103 }] }, cfg).status === 'abgelehnt');
  const smallLevels = { status: 'bereit', direction: 1, entry: 100, sl: 99, tps: [102, 103, 104], risk: 1, rewardRisk: 2, tickSize: .1 };
  const make = (overrides, instrument = 'BTCUSDT') => S.po3Signal({ instrument, levels: smallLevels, confirmedAt: at, sweep, setupSweep: sweep, zone, score: unknown, box, source: { dataRevision: 'bitget-v1', origin: 'rekonstruiert', venue: 'bitget', product: 'USDT-FUTURES', observedAt: at } }, { ...cfg, ...overrides });
  const full = make(), future = [c(0, 100, 102.1, 99.5, 102)];
  check('Close-Modell prüft Exit erst in Folgekerze und schließt vollständig TP1', S.simulatePo3(full, [c(-1, 100, 110, 90, 100), ...future], at + M).outcome === 'tp1');
  const limit = make({ entryMode: 'limit' }), intrabar = S.simulatePo3(limit, [c(0, 101, 103, 99.5, 102)], at + M);
  check('Intrabar Limit+TP: eröffnet, kein TP derselben Minute', intrabar.status === 'Offen' && intrabar.entryAt === at + M && !intrabar.tpsHit.length);
  check('Am Open ausführbares Limit erlaubt TP derselben Minute', S.simulatePo3(limit, [c(0, 100, 102.1, 99.5, 102)], at + M).outcome === 'tp1');
  check('Intrabar Limit+SL+TP konservativ SL, kein Vorab-Verwerfen eines möglichen Fills', S.simulatePo3(limit, [c(0, 101, 103, 98, 98.5)], at + M).outcome === 'sl');
  check('Stop-Gap zum schlechteren Open', S.simulatePo3(full, [c(0, 98, 99, 97, 98)], at + M).netR < -2);
  const notFilled = Array.from({ length: 21 }, (_, i) => c(i, 101, 101.5, 100.5, 101));
  check('Ungefülltes Limit nach 20 Kerzen verfallen', S.simulatePo3(limit, notFilled, at + 21 * M).status === 'Verfallen');
  const opened = [c(0, 101, 101.5, 99.5, 100), ...Array.from({ length: 30 }, (_, i) => c(i + 1, 100.5, 101, 100.1, 100.5))];
  check('Eröffneter Trade verfällt nicht nach 20 Entrykerzen', S.simulatePo3(limit, opened, at + 31 * M).status === 'Offen');
  check('Fehlende Folgekerze bleibt Datenlücke und nie erfundener Timeout/TP', S.simulatePo3(full, [c(1)], at + 2 * M).dataGap && S.simulatePo3(full, [c(1)], at + 2 * M).netR === null);
  const thirds = make({ closure: 'thirds' }), partial = S.simulatePo3(thirds, [c(0, 100, 102.1, 99.5, 102), c(1, 100, 101, 98.5, 99)], at + 2 * M);
  check('Ein Drittel +2R, zwei Drittel −1R: brutto 0R, nach Gebühren negativ', Math.abs(partial.grossR) < 1e-9 && partial.netR < 0 && partial.tpsHit.includes(1));
  check('Ergebnisse ausdrücklich vor Funding, nie vollständiges Netto für Bot-Grenzen', partial.completeNet === false && partial.fundingComplete === false && /vor Funding/.test(partial.costsLabel));
  check('Wiederholung unveränderter Historie idempotent, Originalplan unverändert', JSON.stringify(S.simulatePo3(partial, [c(0, 100, 102.1, 99.5, 102), c(1, 100, 101, 98.5, 99)], at + 2 * M)) === JSON.stringify(partial) && full.status === 'Offen');
  const finished = S.simulatePo3(full, future, at + M), statsArgs = { key: full.parametersKey, from: at, to: at + 2 * M, origin: 'rekonstruiert' };
  check('Journal 29/30: Quote erst ab 30 und TP1-Erfolg separat vom Gesamtnetto', S.po3JournalStats(Array.from({ length: 29 }, (_, i) => S.simulatePo3(make({}, 'TEST' + i + 'USDT'), future, at + M)), statsArgs).tpPercent === null && S.po3JournalStats(Array.from({ length: 30 }, (_, i) => S.simulatePo3(make({}, 'TEST' + i + 'USDT'), future, at + M)), statsArgs).tpPercent === 100);
  check('Dublettenkopie zählt einmal, widersprüchliche ID wird ausgeschlossen', S.po3JournalStats(Array(30).fill(finished), statsArgs).n === 1 && S.po3JournalStats([finished, { ...finished, outcome: 'sl' }], statsArgs).n === 0);
  const step1 = S.advancePo3Signal(thirds, [c(0, 100, 102.1, 99.5, 102)], at + M), step2 = S.advancePo3Signal(step1, [c(0, 100, 102.1, 99.5, 102), c(1, 100, 101, 98.5, 99)], at + 2 * M);
  check('Abschnitte erhalten Teilziel, Gebühren und offene Restmenge; kein Doppel-Fill', JSON.stringify(step2) === JSON.stringify(partial));
  const gap = S.advancePo3Signal(full, [c(1)], at + 2 * M), repaired = S.advancePo3Signal(gap, [c(0, 100, 102.1, 99.5, 102), c(1)], at + 2 * M);
  check('Neustart nach Datenlücke lädt ab fehlender Kerze und löst danach auf', gap.needsFrom === at && repaired.outcome === 'tp1' && !repaired.dataGap);
  check('Änderung bereits verarbeiteter Preisreferenz markiert Konflikt', S.advancePo3Signal(step1, [c(0, 100, 102.2, 99.5, 102)], at + M).priceConflict === true);
  const size = P.po3Size({ balanceUSDT: 1000, riskPercent: 1, leverage: 20, levels: smallLevels, quantityStep: .001 }, cfg);
  check('Eigene Risikogröße inklusive Gebühren, Marginbegrenzung ohne zweites Hebeln', size.riskUSDT <= 10 && size.margin <= 1000 && P.po3Size({ levels: smallLevels, quantityStep: .001 }, cfg).quantity === null);
  console.log(`${pass}/${pass + fail} bestanden`); process.exitCode = fail ? 1 : 0;
})().catch(e => { console.error(e); process.exitCode = 1; });
