// G10(b): echter öffentlicher Adapter mit festen Antworten und gemeinsamer Indikatorrechnung.
const path = require('path'), { pathToFileURL } = require('url');
let pass = 0, fail = 0;
const check = (name, ok) => { ok ? pass++ : fail++; console.log(`${ok ? '✓' : '✗'} ${name}`); };
const throws = fn => { try { fn(); return false; } catch { return true; } };
(async () => {
  const B = await import(pathToFileURL(path.join(__dirname, '../shared/bitget-public.mjs'))), C = await import(pathToFileURL(path.join(__dirname, '../shared/confluence-core.mjs'))), F = await import(pathToFileURL(path.join(__dirname, 'fixtures/bitget.mjs')));
  const { NOW, HOUR, row, transport, selection } = F, p = { patternWeight: 0 }, selected = selection();
  const ctx = { timeframe: '1h', from: NOW - 25 * 60e3 - 2 * HOUR, to: NOW - 25 * 60e3, knownAt: NOW };
  const r1 = row(ctx.from, HOUR), r2 = row(ctx.from + HOUR, HOUR);
  const normalized = B.normalizeBitgetCandles([r2, r1, r1, row(ctx.to, HOUR)], ctx);
  check('UTC-Zeiten, sortierte geschlossene Kerzen; identische Dublette einmal, laufende Kerze ausgeschlossen', normalized.length === 2 && normalized[0].time === ctx.from && normalized[1].end === ctx.to);
  check('Volumen ist Basisvolumen (Feld 5), kein USDT-Quotevolumen (Feld 6)', normalized[0].volume === Number(r1[5]) && normalized[0].volume !== Number(r1[6]));
  check('Tatsächliche Kenntniszeit ist die Empfangszeit, nicht rückdatierter Kerzenschluss', normalized.every(c => c.knownAt === NOW && c.knownAt > c.end));
  check('Falsche UTC-Grenze wird abgelehnt', throws(() => B.normalizeBitgetCandles([[String(ctx.from + 1), ...r1.slice(1)]], ctx)));
  check('Ungültige OHLC und leerer Zahlenwert werden nicht zu null/0 umgedeutet', throws(() => B.normalizeBitgetCandles([[r1[0], '100', '1', '99', '100', '10', '1000']], ctx)) && throws(() => B.normalizeBitgetCandles([[...r1.slice(0, 5), '', '10']], ctx)));
  check('Widersprüchliche Dublette bleibt Fehler', throws(() => B.normalizeBitgetCandles([r1, [...r1.slice(0, 5), '1', '2']], ctx)));
  check('Innere Kerzenlücke bleibt Fehler', throws(() => B.normalizeBitgetCandles([r1, row(ctx.from + 2 * HOUR, HOUR)], { ...ctx, to: ctx.to + HOUR, knownAt: NOW + HOUR })));
  const con = B.normalizeBitgetContract([F.contract], 'BTCUSDT');
  check('Tickgröße = Endschritt × 10^-Nachkommastellen (5 × 0,1)', con.tickSize === .5 && con.quantityStep === .001 && con.minNotional === 5);
  for (const [name, change] of [['Spot', { symbolType: 'spot' }], ['USDC', { quoteCoin: 'USDC' }], ['inaktiv', { symbolStatus: 'off' }], ['ohne Tick', { priceEndStep: '' }], ['ohne USDT-Margin', { supportMarginCoins: ['USDC'] }]]) check(`Kontrakt ${name} ist nicht nutzbar`, throws(() => B.normalizeBitgetContract([{ ...F.contract, ...change }], 'BTCUSDT')));
  check('Falscher/doppelter Symboltreffer wird abgelehnt', throws(() => B.normalizeBitgetContract([F.contract], 'ETHUSDT')) && throws(() => B.normalizeBitgetContract([F.contract, F.contract], 'BTCUSDT')));

  const t = transport(), loaded = await t.client.load({ selection: selected, config: p });
  check('Öffentliche Daten vollständig: Basis und Kontext mit eigenem EMA200', loaded.status === 'bereit' && loaded.data.base.ema200 !== null && loaded.data.context.ema200 !== null);
  check('Ausschließlich Bitget-USDT-Futures, nur GET, keine privaten Pfade/Headers/Body/Cookies', t.calls.every(x => new URL(x.url).origin === B.BITGET_ORIGIN && new URL(x.url).pathname.startsWith('/api/v2/mix/market/') && new URL(x.url).searchParams.get('productType') === 'USDT-FUTURES' && x.init.method === 'GET' && x.init.credentials === 'omit' && x.init.redirect === 'error' && !x.init.body && Object.keys(x.init.headers).join() === 'Accept'));
  check('Begrenzte Seiten statt unbegrenzter Gesamtabruf', t.calls.filter(x => x.url.includes('history-candles')).length === 4 && t.calls.every(x => !x.url.includes('limit=') || Number(new URL(x.url).searchParams.get('limit')) <= 200));
  check('Ältere Rohdaten erhalten keine erfundene historische Fundingabrechnung', loaded.data.funding.kind === 'current' && !loaded.data.funding.costsComplete && loaded.data.funding.intervalHours === 2 && C.normalizeFunding(loaded.data.funding, loaded.data.scope.asOf) === -.0004);
  check('Gemeinsamer G10-Kern bewertet tatsächliche Adapterdaten, keine Quellen-/Indikatorkopie', C.scoreConfluence({ ...loaded.data, direction: 1 }, p).score !== null);
  check('Noch keine Musteranalyse: Standard-W bleibt nicht bewertbar, kein Binance-Musterersatz', loaded.data.patterns === null);
  const savedJSON = JSON.stringify(loaded.saved); t.setNow(NOW + 4 * HOUR); const since = t.calls.length;
  const next = await t.client.load({ selection: selected, config: p, saved: JSON.parse(savedJSON) });
  check('JSON-Fortsetzung behält beide Startanker und ändert alte Eingabe nicht', next.status === 'bereit' && next.saved.series.base.before.anchor === selected.indicatorAnchors.base && next.saved.series.context.before.anchor === selected.indicatorAnchors.context && JSON.stringify(loaded.saved) === savedJSON);
  check('Nur neue Kerzen plus je eine gespeicherte Kontrollkerze geladen', t.calls.slice(since).filter(x => x.url.includes('history-candles')).map(x => Number(new URL(x.url).searchParams.get('limit'))).join() === '5,2');
  const full = await t.client.load({ selection: selected, config: p });
  check('Fortsetzung und neuer Lauf ab denselben festen Ankern ergeben exakt dieselben Indikatoren', ['base', 'context'].every(k => ['price', 'ema50', 'ema200', 'atr'].every(f => next.data[k][f] === full.data[k][f])));
  const beforeCalls = t.calls.length, wrong = await t.client.load({ selection: { ...selected, instrument: 'ETHUSDT' }, config: p, saved: loaded.saved });
  check('Coin-/Parameterwechsel übernimmt fremden Zustand nicht und startet keinen Abruf', wrong.data === null && t.calls.length === beforeCalls);
  check('Abweichende Parameter mit gleicher Revision ebenfalls abgelehnt', (await t.client.load({ selection: selected, config: {}, saved: loaded.saved })).data === null);
  const broken = structuredClone(loaded.saved); broken.series.base.before.count++;
  check('Beschädigter gespeicherter Zustand bleibt nicht bewertbar', (await t.client.load({ selection: selected, config: p, saved: broken })).data === null);
  for (const [name, value] of [['private Quelle', { ...selected, venue: 'binance' }], ['1m-Signalbasis', { ...selected, timeframe: '1m' }], ['kein höherer Kontext', { ...selected, contextTimeframe: '1h' }], ['fehlender Startanker', { ...selected, indicatorAnchors: null }], ['fehlendes Haltemodell', { ...selected, maxHoldMs: null }]]) check(`Ungültige Auswahl: ${name}`, (await t.client.load({ selection: value, config: p })).data === null);
  const gap = transport({ mutate(body, u) { if (u.pathname.endsWith('history-candles')) body.data.pop(); } });
  check('Fehlende erste Kerze/Listing-Warm-up verhindert Score statt kürzerer EMA', (await gap.client.load({ selection: selected, config: p })).data === null);
  const revised = transport({ mutate(body, u) { if (u.pathname.endsWith('history-candles')) body.data.at(-1)[5] = '99999'; } });
  check('Nachträglich abweichende Kontrollkerze wird nicht still überschrieben', (await revised.client.load({ selection: selected, config: p, saved: loaded.saved })).data === null);
  for (const field of ['fundingRate', 'fundingRateInterval', 'nextUpdate']) {
    const missing = transport({ mutate(body, u) { if (u.pathname.endsWith('current-fund-rate')) delete body.data[0][field]; } }), value = await missing.client.load({ selection: selected, config: p });
    check(`Fehlendes ${field}: Preislevel bleiben möglich, Funding/Score unbekannt`, value.status === 'nicht bewertbar' && value.data?.contract.tickSize === .5 && value.data.funding === null && C.scoreConfluence({ ...value.data, direction: 1 }, p).score === null);
  }
  const daily = transport(), long = await daily.client.load({ selection: selection('4h', '1d'), config: p });
  check('Tageskerzen ausdrücklich UTC und Jobseiten höchstens 90 Tage', long.status === 'bereit' && daily.calls.filter(x => new URL(x.url).searchParams.get('granularity') === '1Dutc').every(x => Number(new URL(x.url).searchParams.get('limit')) <= 90));
  const large = transport(), many = selection('1h', '4h', 2100), part = await large.client.load({ selection: many, config: p });
  check('Großer Warm-up ist begrenzter Job, keine Scheinfreigabe', part.status === 'nachladen' && !part.data && part.progress.base.pages === 8 && part.saved.series.base.rows.length === 512);
  const finished = await large.client.load({ selection: many, config: p, saved: part.saved });
  check('Mehrere Jobaufrufe setzen ab Originalanker fort, Kontext ebenfalls begrenzt', finished.status === 'nachladen' && finished.progress.context.pages === 8 && finished.saved.series.base.before.anchor === many.indicatorAnchors.base);
  const ready = await large.client.load({ selection: many, config: p, saved: finished.saved });
  check('Nach begrenzten Jobs verfügbar: keine historische Vollabdeckung erfunden', ready.status === 'bereit' && ready.saved.series.base.before.count === 2100 - 512);
  const fresh = transport(), stop = new AbortController(); stop.abort();
  check('Abbruch verwirft Job, keine API-Abfrage', (await fresh.client.load({ selection: selected, signal: stop.signal })).status === 'abgebrochen' && fresh.calls.length === 0);
  const throttle = transport({ mutate() { return new Response('', { status: 429, headers: { 'Retry-After': '3' } }); } });
  const blocked = await throttle.client.load({ selection: selected }); await throttle.client.load({ selection: selected });
  check('429 mit Retry-After: gemeinsamer Cooldown, keine sofortige Wiederholung', blocked.retryAt === NOW + 3000 && throttle.calls.length === 1);
  const stale = transport({ mutate(body) { body.requestTime -= 30001; } });
  check('Veraltete Providerzeit sperrt, keine alten Antworten als Live-Daten', (await stale.client.load({ selection: selected })).data === null);
  const future = transport({ mutate(body) { body.requestTime++; } });
  check('Zukünftige Providerzeit sperrt', (await future.client.load({ selection: selected })).data === null);
  const parallel = transport(); await Promise.all([parallel.client.load({ selection: selected }), parallel.client.load({ selection: selected })]);
  check('Ein Client serialisiert gleichzeitige Aufrufe', parallel.maxActive === 1);
  const noWarmup = transport();
  check('Nur 199 Kerzen ergeben keinen EMA200-Trend', (await noWarmup.client.load({ selection: selection('1h', '4h', 199), config: p })).data === null);
  const wrongFunding = transport({ mutate(body, u) { if (u.pathname.endsWith('current-fund-rate')) body.data[0].symbol = 'ETHUSDT'; } });
  check('Funding eines anderen Coins verhindert den Score', (await wrongFunding.client.load({ selection: selected, config: p })).data.funding === null);
  const apiError = transport({ mutate(body) { body.code = '40000'; } });
  check('HTTP 200 mit Bitget-Fehlercode ist kein Datenbeleg', (await apiError.client.load({ selection: selected })).data === null);
  const html = transport({ mutate() { return new Response('<html>Fehler</html>', { status: 200 }); } });
  check('HTML statt JSON: deutscher Fehler und keine Freigabe', /kein gültiges JSON/.test((await html.client.load({ selection: selected })).reason));
  const huge = transport({ mutate() { return new Response('x'.repeat(1024 * 1024 + 1), { status: 200 }); } });
  check('Zu große Antwort wird nicht ausgewertet', /Größenbegrenzung/.test((await huge.client.load({ selection: selected })).reason));
  const multibyte = transport({ mutate() { return new Response('€'.repeat(400000), { status: 200 }); } });
  check('Größenbudget gilt für Bytes, auch bei Mehrbytezeichen', /Größenbegrenzung/.test((await multibyte.client.load({ selection: selected })).reason));
  let canceled = false;
  const stream = transport({ mutate() { return new Response(new ReadableStream({ pull(c) { c.enqueue(new Uint8Array(700000)); }, cancel() { canceled = true; } }), { status: 200 }); } });
  check('Übergroßer Antwortstrom wird früh abgebrochen statt vollständig geladen', /Größenbegrenzung/.test((await stream.client.load({ selection: selected })).reason) && canceled);
  const expiredSaved = structuredClone(loaded.saved); expiredSaved.series.context.rows.at(-1).knownAt = NOW + 99 * HOUR;
  check('Gespeicherte zukünftige Kenntniszeit bleibt gesperrt', (await t.client.load({ selection: selected, config: p, saved: expiredSaved })).data === null);
  const hung = B.createBitgetPublicClient({ now: () => NOW, spacingMs: 0, timeoutMs: 10, fetch: (url, init) => new Promise((resolve, reject) => { init.signal.addEventListener('abort', () => reject(init.signal.reason), { once: true }); }) });
  check('Hängender öffentlicher Abruf endet mit Timeout statt endlosem Job', /dauert zu lange/.test((await hung.load({ selection: selected })).reason));
  console.log(`${pass}/${pass + fail} bestanden`); process.exitCode = fail ? 1 : 0;
})().catch(e => { console.error(e); process.exitCode = 1; });
