// G09 C6b: identische Engine, echte feste Kerzen, Dienst ohne App, Revision/Epoche, genau ein Sender, Neustart.
const fs = require('fs'), path = require('path'), os = require('os'), vm = require('vm');
let pass = 0, fail = 0;
const check = (name, ok, info = '') => { ok ? pass++ : fail++; console.log(`${ok ? '✓' : '✗'} ${name}${info ? ' — ' + String(info).slice(0, 500) : ''}`); };
const throws = fn => { try { fn(); return false; } catch { return true; } };
(async () => {
  const W = await import('../server/scalpdesk-247.mjs'), P = await import('../server/pattern-monitor.mjs'), E = await import('../server/pattern-engine.mjs');
  const html = fs.readFileSync(path.join(__dirname, '../weather-widget-v2.html'), 'utf8'), start = html.indexOf('function patEngine() {'), end = html.indexOf('\n// ---- 3.37.0 (G09): zentrale Musterbibliothek', start), source = html.slice(start, end).trim();
  check('Engine im Dienst ist exakt der App-Quelltext (ohne eigene Rechenregeln)', E.patEngine.toString() === source);
  const appEngine = vm.runInNewContext(`(${source})()`), serverEngine = E.patEngine();
  const catalog = fs.readFileSync(path.join(__dirname, 'm58.js'), 'utf8');
  const build = vm.runInNewContext(catalog.slice(catalog.indexOf('const BUILD = () => {'), catalog.indexOf('\nconst tests = {')) + '\nBUILD()');
  const same = Object.entries(build.F).every(([id, pts]) => { const k = build.path(pts), opt = { from: 15, step: build.STEP }; return JSON.stringify(appEngine.detect(k, opt)) === JSON.stringify(serverEngine.detect(k, opt)) && serverEngine.detect(k, opt).hits.some(h => h.id === id); });
  check('Alle 19 Formationen auf denselben festen Katalogreihen in App und Dienst identisch', same);
  check('Deutsche Namen vollständig aus demselben Katalog erzeugt', Object.keys(E.PAT_NAMES).length === 19 && E.PAT_NAMES.double_bottom === 'Doppel-Boden');
  let k = build.path(build.F.double_bottom).map((c, i) => ({ ...c, v: i < 30 ? 100 : 80 })), hit = serverEngine.detect(k, { from: 0, step: build.STEP }).hits.find(h => h.id === 'double_bottom' && /^Ausbruch/.test(h.status));
  if (!hit) throw new Error('Feste Ausbruchsreihe fehlt.');
  k = k.slice(0, hit.i1 + 1);
  let now = P.patternEnd(k.at(-1).t, '1h') + 2000;
  const item = { mkt: 'spot', sym: 'BTCUSDT', iv: '1h' }, rows = () => k.map(c => [c.t, c.o, c.h, c.l, c.c, c.v, P.patternEnd(c.t, '1h') - 1]);
  const found = P.patternCases(k, item, now), pair = found.find(x => x.c.pat === 'double_bottom');
  check('Echte Engine erkennt frisch bestätigten Doppel-Boden mit Regelgüte ≥ 80', !!pair, JSON.stringify(found.map(x => [x.c.pat, x.c.q])));
  if (!pair) throw new Error('Frische Formation fehlt.');
  const { c, h } = pair;
  check('Fall-ID ist exakt der bestehende App-/Archivvertrag, keine neue Preis-/Geräte-ID', c.id === W.caseId(c) && c.id === `${c.mkt}|${c.sym}|${c.iv}|${c.pat}|${c.t0}|${c.t1}|pat-1`);
  const open = [...rows(), [P.patternEnd(k.at(-1).t, '1h'), 999, 1000, 998, 999, 1, P.patternEnd(P.patternEnd(k.at(-1).t, '1h'), '1h') - 1]];
  check('Laufende Kerze wird vor der Engine entfernt; keine Zukunftskerzen', JSON.stringify(P.patternCandles(open, '1h', now)) === JSON.stringify(k));
  const invalid = rows(); invalid[5][2] = 0;
  check('Ungültiges OHLC und Kerzenlücken werden sichtbar abgelehnt', throws(() => P.patternCandles(invalid, '1h', now)) && throws(() => P.patternCandles(rows().filter((_, i) => i !== 5), '1h', now)));
  check('Veraltete API-Daten sperren frische Meldungen', throws(() => P.patternCases(k, item, now + 3 * 36e5)));
  check('Monatsende kalendergenau einschließlich Februar, kein 30-Tage-Ersatz', P.patternEnd(Date.UTC(2026, 1, 1), '1M') === Date.UTC(2026, 2, 1));
  const token = '123456789:TEST_ONLY_not_a_real_token_000000000', key = 'k'.repeat(43), dir = fs.mkdtempSync(path.join(os.tmpdir(), 's247e-')), logs = [], sent = [];
  // Jeder unabhängige Dienst startet vor dem Schluss der festen Bestätigungskerze.
  const make = (name, extra = {}) => { now = c.tc + 1; return new W.Watcher({ token, chat: '111', key, listen: '127.0.0.1:0', statePath: path.join(dir, name, 'state.json'), now: () => now, log: (...x) => logs.push(x.join(' ')), patternFetch: async () => rows(), ...extra }); };
  const config = { items: [item], bot: token.split(':')[0], chat: '-100888', thread: '77' };
  const w = make('haupt');
  const cfg = (watcher, id = 'watch-cmd-0001', conf = config, revision = watcher.patternWatch.rev) => watcher.applyPatternWatch({ commandId: id, expectedRevision: revision, config: conf });
  now = c.tc + 1; let r = cfg(w);
  check('Musterliste versioniert dauerhaft übernommen, kein Telegram-Token im Vertrag', r.status === 200 && w.patternWatch.rev === 1 && !JSON.stringify(w.patternWatch).includes(token));
  check('Gleicher Command nach verlorener Antwort ändert Revision nicht', cfg(w).body.repeat && w.patternWatch.rev === 1);
  check('Konkurrierende veraltete Revision abgelehnt, bisheriger Stand bleibt', cfg(w, 'watch-cmd-0002', { ...config, chat: '-100999' }, 0).status === 409 && w.patternWatch.config.chat === config.chat);
  check('Ungültiger Markt, doppelte Märkte und unbekanntes Intervall abgelehnt', cfg(w, 'watch-bad-0001', { ...config, items: [{ ...item, mkt: 'bitget' }] }).status === 400 && cfg(w, 'watch-bad-0002', { ...config, items: [item, item] }).status === 400 && cfg(w, 'watch-bad-0003', { ...config, items: [{ ...item, iv: '30d' }] }).status === 400);
  check('Unbekannter Muster-Bot wird nicht durch den Kursalarmbot ersetzt', cfg(w, 'watch-bot-0001', { ...config, bot: '999999' }).status === 400);
  now = P.patternEnd(c.tc, c.iv) + 2000;
  w.tg = async (method, body, timeout, usedToken) => { sent.push({ method, body, usedToken }); return { message_id: sent.length }; };
  await w.checkPatterns();
  const ev = `pat:${c.id}`, messages = sent.filter(x => x.body.text?.includes('Doppel-Boden'));
  check('App geschlossen: echte Erkennung sendet an Musterchat/Thema, nicht Kursalarm', messages.length === 1 && messages[0].body.chat_id === config.chat && messages[0].body.message_thread_id === config.thread && messages[0].usedToken === token);
  check('Gleiche echte Ereignis-ID dauerhaft für oracle bestätigt', w.evs[ev]?.st === 'confirmed' && w.evs[ev]?.by === 'oracle' && w.evs[ev]?.target === 'patterns');
  check('Meldung erklärt Regelgüte, Ziel, Invalidierung und fehlende erlernte Statistik', /Regelbasiert \(Modell pat-1\)/.test(messages[0]?.body.text) && /rechnerisches Ziel/.test(messages[0]?.body.text) && /ungültig bei/.test(messages[0]?.body.text) && /noch zu wenige vergleichbare Fälle/.test(messages[0]?.body.text) && /keine Erfolgswahrscheinlichkeit/.test(messages[0]?.body.text));
  const before = sent.length; await Promise.all([w.notifyPattern(c, h), w.notifyPattern(c, h)]); await w.checkPatterns();
  check('Dienstprüfung und zwei offene Geräte melden denselben Fall insgesamt einmal', sent.length === before);
  w.saveStateNow(); const restarted = make('haupt'); now = P.patternEnd(c.tc, c.iv) + 2000; restarted.tg = w.tg; await restarted.checkPatterns();
  check('Neustart erhält Liste, Revision und Dublettensperre', restarted.patternWatch.rev === 1 && restarted.evs[ev]?.st === 'confirmed' && sent.length === before);
  const appFirst = make('app-zuerst'); now = c.tc + 1; cfg(appFirst); now = P.patternEnd(c.tc, c.iv) + 2000;
  const reserved = W.evReserve(appFirst.evs, appFirst.pol, { eventId: ev, targetId: 'patterns', sender: 'app:iphone1' }, now);
  appFirst.tg = w.tg; await appFirst.notifyPattern(c, h);
  check('Echte Fall-ID mit | ist zulässig; ältere Appfreigabe verhindert zweiten Dienstversand', reserved.status === 200 && reserved.body.grant && sent.length === before);
  const off = make('aus'); now = c.tc + 1; cfg(off); off.tg = w.tg;
  W.policyApply(off.pol, off.cmds, { commandId: 'off-cmd-0001', expectedRevision: 0, set: { patterns: false } }, now);
  now = P.patternEnd(c.tc, c.iv) + 2000; await off.checkPatterns();
  check('Ziel AUS: keine Muster-Abrufe oder Meldungen', sent.length === before && off.patternProgress.size === 0);
  W.policyApply(off.pol, off.cmds, { commandId: 'on-cmd-00001', expectedRevision: 1, set: { patterns: true } }, now);
  await off.checkPatterns();
  check('Erneutes AN holt vor dem Einschalten bestätigte Fälle nicht nach', sent.length === before);
  const failing = make('speicherfehler'); failing.saveStateNow = () => false;
  check('Speicherfehler bestätigt keine neue Liste und belässt alten Stand', cfg(failing).status === 503 && failing.patternWatch.rev === 0);
  const queue = make('ausgang'); now = c.tc + 1; cfg(queue); now = P.patternEnd(c.tc, c.iv) + 2000;
  queue.tg = async () => { throw Object.assign(new Error('Telegram nicht erreichbar'), { code: 0 }); };
  await queue.notifyPattern(c, h);
  check('Sicherer Verbindungsfehler: Muster bleibt mit Ziel und Epoche im dauerhaften Ausgang', queue.out.length > 0 && queue.out[0].target === 'patterns' && !fs.readFileSync(queue.statePath, 'utf8').includes(token));
  W.policyApply(queue.pol, queue.cmds, { commandId: 'queue-off-0001', expectedRevision: 0, set: { patterns: false } }, now);
  W.policyApply(queue.pol, queue.cmds, { commandId: 'queue-on-00001', expectedRevision: 1, set: { patterns: true } }, now);
  now += 60e3; queue.tg = w.tg; await queue.deliver();
  check('AUS/AN verwirft alte Ausgangsepoche, keine Nachlieferung', queue.out.length === 0 && queue.evs[ev].st === 'discarded' && sent.length === before);
  const lost = make('antwort-verloren'); now = c.tc + 1; cfg(lost); now = P.patternEnd(c.tc, c.iv) + 2000; let attempts = 0;
  lost.tg = async () => { attempts++; throw Object.assign(new Error('Antwort verloren'), { lost: true }); };
  await lost.notifyPattern(c, h); await lost.notifyPattern(c, h); await lost.deliver();
  check('Verlorene Telegram-Antwort: unbestätigt, genau ein Versuch', attempts === 1 && lost.evs[ev].st === 'unconfirmed' && lost.out.length === 0);
  const during = make('wechsel-im-abruf'); now = c.tc + 1; cfg(during); now = P.patternEnd(c.tc, c.iv) + 2000;
  during.tg = w.tg; during.patternFetch = async () => { W.policyApply(during.pol, during.cmds, { commandId: 'during-off-01', expectedRevision: 0, set: { patterns: false } }, now); return rows(); };
  await during.checkPatterns();
  check('Ausschalten während Markt-Abruf verwirft die Antwort', sent.length === before && Object.keys(during.evs).length === 0);
  const crash = make('prozessabbruch'); cfg(crash); now = P.patternEnd(c.tc, c.iv) + 2000;
  let resumed, entered; const began = new Promise(resolve => { entered = resolve; });
  crash.tg = async () => { entered(); await new Promise(resolve => { resumed = resolve; }); return { message_id: 1 }; };
  const delivery = crash.notifyPattern(c, h); await began;
  const recovered = make('prozessabbruch'); now = P.patternEnd(c.tc, c.iv) + 2000; recovered.tg = w.tg; await recovered.deliver(); await recovered.notifyPattern(c, h);
  check('Prozessabbruch während Telegram-POST: nach Neustart unbestätigt, kein zweiter POST', recovered.evs[ev]?.st === 'unconfirmed' && recovered.out.length === 0 && sent.length === before);
  resumed(); await delivery;
  const parallel = make('parallel'); cfg(parallel); now = P.patternEnd(c.tc, c.iv) + 2000; let concurrent = 0;
  parallel.tg = async () => { concurrent++; await new Promise(r => setTimeout(r, 5)); return { message_id: 1 }; };
  await Promise.all([parallel.notifyPattern(c, h), parallel.notifyPattern(c, h), parallel.deliver()]);
  check('Gleichzeitige Dienst-/HTTP-Takte serialisieren den Ausgang', concurrent === 1);
  const countFetch = make('scheduler'); cfg(countFetch); now = P.patternEnd(c.tc, c.iv) + 2000; let fetched = 0;
  countFetch.patternFetch = async () => { fetched++; return rows(); }; countFetch.tg = async () => ({ message_id: 1 });
  await countFetch.checkPatterns(); await countFetch.checkPatterns();
  check('Kein wiederholter Historienabruf innerhalb derselben Kerze', fetched === 1);
  const changed = make('liste-im-abruf'); cfg(changed); now = P.patternEnd(c.tc, c.iv) + 2000;
  changed.patternFetch = async () => { cfg(changed, 'list-changed-01', { ...config, items: [] }); return rows(); }; changed.tg = w.tg;
  await changed.checkPatterns();
  check('Geänderte Liste während des Abrufs verwirft überholte Antwort', sent.length === before && Object.keys(changed.evs).length === 0);
  const otherToken = '222222222:TEST_ONLY_not_a_real_token_000000000', ownBot = make('eigener-bot', { patternToken: otherToken });
  const own = cfg(ownBot, 'own-bot-00001', { ...config, bot: '222222222' });
  check('Eigener Serverbot über ID gewählt; beide Token werden aus Fehlertexten entfernt', own.status === 200 && ownBot.patternDestination(ownBot.patternWatch.config) === otherToken && !ownBot.secret(`${token} ${otherToken}`).includes('TEST_ONLY'));
  check('Frischefilter sperrt unbestätigte, schwache und ältere Fälle', !P.patternFresh({ ...c, q: 79 }, now, 0) && !P.patternFresh({ ...c, src: 'rekonstruiert' }, now, 0) && !P.patternFresh(c, now + 3 * 36e5, 0));
  const detached = make('langsamer-markt'); cfg(detached); now = P.patternEnd(c.tc, c.iv) + 2000;
  let releaseFetch; detached.syncConfig = async () => {}; detached.tg = async () => ({ message_id: 1 });
  detached.patternFetch = () => new Promise(resolve => { releaseFetch = resolve; });
  await detached.tick();
  check('Langsamer Muster-Abruf blockiert den bisherigen Diensttakt nicht', detached.patternBusy && typeof releaseFetch === 'function');
  releaseFetch(rows()); while (detached.patternBusy) await new Promise(resolve => setTimeout(resolve, 5));
  now = P.patternEnd(c.tc, c.iv) + 2000;
  const port = await w.listenNow(), call = (route, body, auth = key, origin = 'https://nicoahb.github.io') => fetch(`http://127.0.0.1:${port}${route}`, { method: body ? 'POST' : 'GET', headers: { authorization: `Bearer ${auth}`, origin, 'content-type': 'application/json' }, ...(body ? { body: JSON.stringify(body) } : {}) });
  check('Muster-Endpunkte prüfen Schlüssel und Herkunft', (await call('/v1/patterns/watch', {}, 'falsch')).status === 401 && (await call('/v1/patterns/watch', {}, key, 'https://fremd.invalid')).status === 403);
  check('App-Meldung mit veralteter Musterrevision wird vor Versand abgelehnt', (await call('/v1/patterns/notify', { expectedRevision: 0, c, levels: h.levels })).status === 409);
  const response = await (await call('/v1/patterns/notify', { expectedRevision: 1, c, levels: h.levels })).json();
  check('HTTP-Meldung eines bereits gesendeten Falls bleibt idempotent', response.ok && response.reason === 'already-reserved' && sent.length === before);
  check('Status/Protokoll/Zustand enthalten keine Bot-Token oder Dienstschlüssel', !JSON.stringify(w.stateView()).includes(token) && !JSON.stringify(logs).includes(token) && !JSON.stringify(logs).includes(key) && !fs.readFileSync(w.statePath, 'utf8').includes(key));
  w.server.close();
  for (const watcher of [w, restarted, appFirst, off, failing, queue, lost, during, crash, recovered, parallel, countFetch, changed, ownBot, detached]) { clearTimeout(watcher.saveTimer); clearTimeout(watcher.arch?.timer); }
  fs.rmSync(dir, { recursive: true, force: true });
  console.log(`\n${pass}/${pass + fail} bestanden`); process.exit(fail ? 1 : 0);
})().catch(e => { console.error(e); process.exit(1); });
