// G12: lokale/Oracle-Laufsimulation. Keine privaten Schlüssel, Orders oder automatischen Moduswechsel.
const doc = () => globalThis.document;
function el(tag, text = '', className = '') { const n = doc().createElement(tag); n.textContent = text; n.className = className; return n; }
const date = x => Number.isFinite(x) ? new Date(x).toLocaleString('de-DE') : 'noch kein Lauf';
const decimal = input => input.value.trim().replace(',', '.');
export function createBotView({ host, globalHost, load, command, exportState, currentSymbol, fxReference, changed, destination = 'local' }) {
  const state = { confirmed: null, destination: destination === 'oracle' ? 'oracle' : 'local', busy: false, message: 'Bot deaktiviert. Simulation einrichten; Demo/Echtgeld gesperrt.' };
  const root = el('section', '', 'bot-view'); root.id = 'bot-view'; root.append(el('h2', 'Trading-Bot · optional'));
  const help = el('details', '', 'ki-info'); help.append(el('summary', 'ⓘ Modus, Stopps und Handlung'), el('p', 'Simulation prüft deine selbst eingegebenen Modellwerte und Laufgrenzen. Sie führt keine Börsenorders aus und simuliert keine automatischen Strategie-Fills. Automatische Trades sind AUS.'),
    el('p', 'Gewinn/Verlust einschließlich Gleichheit: keine neuen Einstiege oder Bot-Bestand schließen. In dieser Simulation wird die Schließwirkung ausdrücklich modelliert; sie ist keine belegte Ausführung. Neue Einzahlung und neuer FX verändern die festgehaltene Laufbasis nicht.'),
    el('p', 'Stopps bleiben nach Kursrückkehr und Neustart verriegelt. Bei Bestandskonflikt: keine neuen Orders und keine Ausgleichsorders. Bereits liegende Schutzorders bleiben bestehen und können auslösen. Nach zehn Sekunden ohne belegten Abgleich dauerhaft pausiert.'),
    el('p', 'Empfehlung: Grenzen zunächst in der Simulation prüfen. Für Demo/Echtgeld fehlen privater Oracle-Executor und bestätigte Kontotyp-/Positionsmodus-/Risikoeinrichtung. Keine Bitget-Schlüssel oder Passwörter in diesem Browser eingeben.')); root.append(help);
  const grid = el('div', '', 'ki-settings-grid'), fields = {};
  function field(key, title, value = '', choices = null) { const label = el('label', title), input = el(choices ? 'select' : 'input'); input.id = 'bot-' + key;
    if (choices) for (const [v, text] of choices) { const o = el('option', text); o.value = v; input.append(o); } else { input.type = 'text'; input.inputMode = 'decimal'; input.maxLength = 64; }
    input.value = value; fields[key] = input; label.append(input); grid.append(label); return input; }
  field('destination', 'Simulation speichern / steuern', state.destination, [['local', 'Lokal · eigener Modelllauf'], ['oracle', 'Oracle · serverbestätigter Modelllauf']]);
  field('mode', 'Erlaubter Modus', 'simulation', [['simulation', 'Simulation · keine Börsenorders'], ['demo', 'Bitget-Demo · gesperrt'], ['live', 'Echtgeld · gesperrt']]);
  field('strategy', 'Strategieprofil · nur Vorbereitung', 'confluence', [['confluence', 'Konfluenz'], ['po3', 'Power of Three']]); field('direction', 'Richtung', 'both', [['both', 'Long + Short'], ['long', 'Long'], ['short', 'Short']]);
  field('referenceUSDT', 'Eigene feste Laufbasis · USDT'); field('riskPercent', 'Selbst gewähltes Risiko · %'); field('exposureUSDT', 'Selbst gewählte maximale Exposition · USDT');
  field('leverage', 'Rechenhebel', '20'); field('maxPositions', 'Maximale Modellpositionen', '1'); field('minimumScore', 'Mindestscore', '70'); field('cooldownMs', 'Cooldown · Sekunden', '60');
  field('stopRule', 'Stop-Regel · Vorbereitung', 'signal', [['signal', 'Preisplan des Signals'], ['own', 'Eigene Regel · vor Adaptereinrichtung klären']]); field('tpRule', 'TP-Regel', 'tp1', [['tp1', 'Vollständig bei TP1'], ['signal', 'Preisplan des Signals']]);
  field('fx', 'Fester EUR/USDT-Startkurs · nur für EUR-Grenze');
  const limits = {}; for (const [key, title] of [['gain', 'Stoppen ab Gewinn'], ['loss', 'Stoppen ab Verlust']]) { const l = el('label', title), check = el('input'); check.type = 'checkbox'; check.id = 'bot-' + key + '-enabled'; l.prepend(check); grid.append(l); limits[key] = check;
    field(key + 'Amount', title + ' · eigener Betrag'); field(key + 'Unit', title + ' · Einheit', 'USDT', [['USDT', 'USDT'], ['EUR', 'EUR · fester Startkurs'], ['%', '% · feste Laufbasis']]);
    field(key + 'Action', title + ' · Wirkung', key === 'loss' ? 'close' : 'entries', [['entries', 'Keine neuen Einstiege · Schutz bleibt'], ['close', 'Bot-Positionen schließen · Modellwirkung']]); }
  root.append(el('h3', 'Einstellungen für den nächsten Modelllauf'), grid); const automated = el('label'), auto = el('input'); auto.type = 'checkbox'; auto.id = 'bot-automatic'; auto.checked = false; auto.disabled = true; automated.append(auto, ' Automatische Trades AUS · Ausführungsadapter fehlt'); root.append(automated); const toolbar = el('div', '', 'ki-toolbar'); root.append(toolbar);
  function button(id, text, fn, parent = toolbar) { const b = el('button', text, 'button ghost'); b.id = id; b.type = 'button'; b.addEventListener('click', fn); parent.append(b); return b; }
  button('bot-load', 'Bestätigten Stand laden', () => refresh());
  const activate = button('bot-enable', 'Bot-Simulation aktivieren', () => send('enable', { enabled: !state.confirmed?.enabled }));
  button('bot-start', 'Bewusst neuen Simulationslauf starten', () => { const at = Date.now(), runId = 'sim-' + at.toString(36) + Math.random().toString(36).slice(2, 8), limit = key => ({ enabled: limits[key].checked, amount: decimal(fields[key + 'Amount']) || null, unit: fields[key + 'Unit'].value, action: fields[key + 'Action'].value });
    const settings = { strategy: fields.strategy.value, coins: [currentSymbol()], direction: fields.direction.value, minimumScore: Number(fields.minimumScore.value), leverage: Number(fields.leverage.value), maxPositions: Number(fields.maxPositions.value), cooldownMs: Number(fields.cooldownMs.value) * 1000,
      stopRule: fields.stopRule.value, tpRule: fields.tpRule.value, exposureUSDT: decimal(fields.exposureUSDT) || null, riskPercent: decimal(fields.riskPercent) || null };
    return send('start', { mode: fields.mode.value, settings, runId, referenceUSDT: decimal(fields.referenceUSDT) || null, fx: decimal(fields.fx) ? { value: decimal(fields.fx), at, source: 'selbst gewählter Startreferenzkurs' } : null, gain: limit('gain'), loss: limit('loss'),
      restartReview: Object.fromEntries(['positionReviewed', 'historyReviewed', 'protectionReviewed'].map(k => [k, doc().getElementById('bot-review-' + k)?.checked === true])), inventory: { complete: true, at, positions: [], source: 'ausdrücklich geprüfter leerer Modellbestand, keine private Börsenauskunft' },
      snapshot: { runId, at, sequence: 0, currency: 'USDT', completeNet: true, source: 'Simulation · leerer eigener Modelllauf, keine Börsenfills', values: { realized: '0', open: '0', fees: '0', rebates: '0', funding: '0', estimatedCloseFees: '0' } } }); });
  button('bot-pause', 'Keine neuen Modelleinstiege · pausieren', () => send('pause', {}));
  button('bot-fx-use', 'Vorhandenen FX-Referenzkurs übernehmen', () => { const fx = fxReference(); if (!fx) state.message = 'Kein gültiger aktueller Referenzkurs; eigenen Kurs angeben.'; else { fields.fx.value = fx.value; state.message = 'Referenzkurs übernommen; beim Laufstart festgehalten.'; } render(); });
  const review = el('details', '', 'ki-info'); review.append(el('summary', 'Bewusster neuer Modelllauf nach Störung'), el('p', 'Nur Simulation: alten Verlauf sichern und Modellbestand/Historie/Schutzwirkung bewusst prüfen. Hiermit kann kein privater Demo-/Echtgeldbot freigeschaltet werden.')); for (const [k, title] of [['positionReviewed', 'Leeren Modellbestand (0) geprüft'], ['historyReviewed', 'Modellhistorie geprüft'], ['protectionReviewed', 'Modellschutzwirkung geprüft']]) { const l = el('label'), input = el('input'); input.type = 'checkbox'; input.id = 'bot-review-' + k; l.append(input, ' ' + title); review.append(l); } root.append(review);
  fields.destination.addEventListener('change', () => { state.destination = fields.destination.value; state.confirmed = null; changed(state.destination); void refresh(); });
  const status = el('p', '', 'ki-note'); status.id = 'bot-status'; status.setAttribute('role', 'status'); root.append(status);
  const alert = el('div', '', 'ki-tone ki-negative'); alert.id = 'bot-reconciliation'; alert.setAttribute('role', 'alert'); root.append(alert);
  const global = el('div', '', 'ki-tone ki-negative'); global.id = 'bot-global-warning'; global.setAttribute('role', 'alert'); global.hidden = true; globalHost.append(global);
  const summary = el('p', '', 'ki-note'); summary.id = 'bot-run-summary'; root.append(summary);
  const scenario = el('details', '', 'ki-info'); scenario.id = 'bot-scenario'; scenario.append(el('summary', 'Modellwerte eingeben · keine Börsendaten'), el('p', 'Werte betreffen nur diesen Modelllauf, in USDT. Brutto realisiert/offen; bezahlte Gebühren positiv, Rabatte positiv, Funding bezahlt positiv/empfangen negativ. Alle sechs Angaben bewusst setzen. Unvollständige PO3-Werte vor Funding sind kein vollständiges Netto.'));
  const scenarioGrid = el('div', '', 'ki-settings-grid'); const valueFields = {};
  for (const [key, label] of [['realized', 'Brutto realisiert · ohne Gebühren'], ['open', 'Brutto offen · ohne Gebühren'], ['fees', 'Bezahlte Gebühren'], ['rebates', 'Gebührenrabatte'], ['funding', 'Vorzeichenbehaftetes Funding'], ['estimatedCloseFees', 'Geschätzte Schließgebühren']]) { const l = el('label', label), input = el('input'); input.type = 'text'; input.inputMode = 'decimal'; input.maxLength = 64; input.id = 'bot-value-' + key; l.append(input); scenarioGrid.append(l); valueFields[key] = input; }
  scenario.append(scenarioGrid); root.append(scenario);
  button('bot-zero-values', 'Alle Modellwerte ausdrücklich auf 0 setzen · Stopps bleiben', () => { for (const input of Object.values(valueFields)) input.value = '0'; }, scenario);
  button('bot-step', 'Modellsnapshot prüfen', () => { const run = state.confirmed?.run; if (!run) { state.message = 'Zuerst bewusst einen Lauf starten.'; render(); return; }
    return send('snapshot', { snapshot: { runId: run.id, at: Date.now(), sequence: run.latest.sequence + 1, currency: 'USDT', completeNet: true, source: 'selbst eingegebene vollständige Modellwerte', values: Object.fromEntries(Object.entries(valueFields).map(([k, input]) => [k, decimal(input)])) } }); }, scenario);
  const close = button('bot-sim-close', 'Schließwirkung ausdrücklich simulieren', () => send('close', {}), scenario);
  button('bot-export', 'Vollständigen Simulationsstand sichern', async () => { try { const text = await exportState(state.destination), a = el('a'), url = URL.createObjectURL(new globalThis.Blob([text], { type: 'application/json' })); a.href = url; a.download = 'scalpdesk-bot-simulation-' + new Date().toISOString().slice(0, 10) + '.json'; a.click(); URL.revokeObjectURL(url); } catch (e) { state.message = e.message; render(); } });
  const log = el('div'); log.id = 'bot-log'; root.append(log); host.append(root);
  async function refresh() { if (state.busy) return; state.busy = true; render(); try { accept(await load(state.destination)); state.message = 'Bestätigter Simulationsstand geladen. Keine automatische Aktivierung und keine Börsenorder.'; } catch (e) { state.message = e.message; } finally { state.busy = false; render(); } }
  async function send(type, parameters) { if (state.busy) return; state.busy = true; render(); try { if (!state.confirmed) accept(await load(state.destination)); accept(await command(state.destination, { type, parameters, expectedRevision: state.confirmed.revision })); state.message = 'Simulationsauftrag dauerhaft bestätigt. Börsenorders und automatische Trades bleiben AUS.'; } catch (e) { state.message = e.message; } finally { state.busy = false; render(); } }
  function accept(confirmed) { state.confirmed = confirmed; changed(state.destination, confirmed); render(); }
  function render() { const s = state.confirmed, r = s?.run, conflicted = ['RECONCILING', 'PAUSED_RECONCILIATION_REQUIRED'].includes(r?.state);
    status.textContent = (state.destination === 'oracle' ? 'Oracle · ' : 'Lokal · ') + state.message + (s?.error ? ' ' + s.error : ''); activate.textContent = s?.enabled ? 'Bot-Simulation deaktivieren' : 'Bot-Simulation aktivieren';
    summary.textContent = r ? `Simulation · Revision ${s.revision} · ${r.state} · Lauf ${date(r.startedAt)} · Netto ${r.netUSDT} USDT · feste Basis ${r.referenceUSDT} USDT · Gewinn ${r.gain.enabled ? r.gain.amount + ' ' + r.gain.unit + ' / ' + r.gain.action : 'AUS'} · Verlust ${r.loss.enabled ? r.loss.amount + ' ' + r.loss.unit + ' / ' + r.loss.action : 'AUS'}${r.fx ? ' · FX ' + r.fx.value : ''}. ${Object.keys(r.stops).length ? 'Grenze dauerhaft verriegelt; bewusst neuer Lauf erforderlich.' : 'Noch keine Laufgrenze berührt.'} Automatische Trades AUS; keine ausgeführten Börsenorders.` : 'Noch kein gestarteter Lauf. Eigene Geld-/Risikobeträge wählen; Aktivierung und Start getrennt.';
    summary.className = 'ki-tone ki-' + (conflicted ? 'negative' : Object.keys(r?.stops ?? {}).length ? 'warning' : r ? 'positive' : 'muted');
    alert.hidden = !conflicted; alert.textContent = conflicted ? `${s.actions.label}. Erwartet ${JSON.stringify(r.inventory.expected ?? {})} / tatsächlich ${JSON.stringify(r.inventory.actual ?? {})} · Datenzeit ${date(r.inventory.at)}. Bestand, Fills und Schutzorders prüfen. Keine automatischen Schließungen/Ausgleichsorders; liegende Schutzorders können weiter auslösen.` : '';
    global.hidden = !conflicted; global.textContent = conflicted ? 'Simulation · ' + s.actions.label + ' · Trading-Bot öffnen und Bestand prüfen.' : '';
    close.disabled = state.busy || !s?.actions?.newCloses || !r?.simulatedClosePending; for (const id of ['bot-enable', 'bot-start', 'bot-pause', 'bot-step', 'bot-load']) doc().getElementById(id).disabled = state.busy;
    if (s) { const key = JSON.stringify([s.revision, s.logs?.slice(-20)]); if (log.dataset.key !== key) { log.replaceChildren(...(s.logs ?? []).slice(-20).reverse().map(x => el('p', `${date(x.at)} · ${x.type} · ${x.state ?? 'deaktiviert'} · Revision ${x.revision}`, 'ki-note'))); log.dataset.key = key; } }
  }
  render(); return { state, accept, render, refresh, send };
}
